'use strict';

const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { DatabaseSync } = require('node:sqlite');
const QRCode = require('qrcode');
const sharp = require('sharp');
const { initialize, audit } = require('./schema');
const { verifyPin, safeEqual, signToken, verifyToken, verifyTotp, randomToken } = require('./security');
const { backfillWeather } = require('./weather');
const rateLimit = require('./ratelimit');
const { renderLabelPage } = require('./labels');
const { recordsCsv, sitesGeoJson, recordsGeoJson, gpx, zipStore } = require('./exports');

const ROOT = path.resolve(__dirname, '..');
const DATA = path.resolve(process.env.DATA_DIR || path.join(ROOT, 'data', 'v1'));
const UPLOADS = path.join(DATA, 'uploads');
const REFERENCE = path.join(DATA, 'reference');
const PUBLIC = path.join(ROOT, 'public');
const CONFIG = path.join(DATA, 'config.json');
fs.mkdirSync(UPLOADS, { recursive: true });
fs.mkdirSync(REFERENCE, { recursive: true });
const MIME = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.svg': 'image/svg+xml', '.png': 'image/png', '.ico': 'image/x-icon' };
let saved = {};
try { saved = JSON.parse(fs.readFileSync(CONFIG, 'utf8')); } catch {}
const config = {
  host: process.env.HOST || saved.host || '127.0.0.1', port: Number(process.env.PORT || saved.port || 3100),
  publicBaseUrl: process.env.PUBLIC_BASE_URL || saved.publicBaseUrl || 'https://bsc.gpsgps.online',
  adminPassword: process.env.ADMIN_PASSWORD || saved.adminPassword || 'ChangeMe-2608!',
  adminTotpSecret: process.env.ADMIN_TOTP_SECRET ?? saved.adminTotpSecret ?? '',
  sessionSecret: process.env.SESSION_SECRET || saved.sessionSecret || randomToken(48), lockHours: 12
};
if (!fs.existsSync(CONFIG)) fs.writeFileSync(CONFIG, JSON.stringify(config, null, 2));
const db = new DatabaseSync(path.join(DATA, 'bsc-v1.sqlite')); initialize(db);

function output(res, status, value, headers = {}) { const body = Buffer.from(JSON.stringify(value)); res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': body.length, 'Cache-Control': 'no-store', ...headers }); res.end(body); }
function error(status, message) { const e = new Error(message); e.status = status; return e; }
async function body(req, max = 12_000_000) { const chunks = []; let size = 0; for await (const chunk of req) { size += chunk.length; if (size > max) throw error(413, '请求过大'); chunks.push(chunk); } try { return chunks.length ? JSON.parse(Buffer.concat(chunks).toString('utf8')) : {}; } catch { throw error(400, 'JSON格式错误'); } }
function bearer(req) { return String(req.headers.authorization || '').replace(/^Bearer\s+/i, ''); }
function admin(req) { const s = verifyToken(config.sessionSecret, bearer(req)); if (!s || s.role !== 'admin') throw error(401, '请登录管理员'); return s; }
function mobile(req) { const s = verifyToken(config.sessionSecret, bearer(req)); if (!s || s.role !== 'villager' || !s.deviceId) throw error(401, '设备登录已过期'); const d = db.prepare('SELECT * FROM devices WHERE id=? AND villager_id=? AND enabled=1').get(s.deviceId, s.subject); if (!d) throw error(403, '设备已停用'); return { ...s, villagerId: Number(s.subject), device: d }; }
function required(value, label) { const text = String(value ?? '').trim(); if (!text) throw error(400, `请填写${label}`); return text; }
function number(value, label) { const n = Number(value); if (!Number.isFinite(n)) throw error(400, `${label}无效`); return n; }
function distance(a, b, c, d) { const r = x => x * Math.PI / 180, x = Math.sin(r(c - a) / 2) ** 2 + Math.cos(r(a)) * Math.cos(r(c)) * Math.sin(r(d - b) / 2) ** 2; return 2 * 6371008.8 * Math.asin(Math.sqrt(x)); }
function transaction(fn) { db.exec('BEGIN IMMEDIATE'); try { const value = fn(); db.exec('COMMIT'); return value; } catch (e) { try { db.exec('ROLLBACK'); } catch {} throw e; } }
function parse(value, fallback = []) { try { return JSON.parse(value); } catch { return fallback; } }
function expire() { db.prepare(`UPDATE tasks SET locked_device_id=NULL,locked_at=NULL,journey_id=NULL,status='assigned' WHERE status='in_progress' AND datetime(locked_at)<datetime('now','-12 hours')`).run(); }
function sampleCode(date, type, site) { const base = `${date.replaceAll('-', '').slice(2)}-${type}-${site.code}`; const count = db.prepare('SELECT COUNT(*) count FROM tasks WHERE planned_date=? AND sample_type=? AND site_id=?').get(date, type, site.id).count + 1; return { base, count, code: `${base}-${String(count).padStart(2, '0')}` }; }
function ipOf(req) { return String(req.headers['x-forwarded-for'] || '').split(',')[0].trim() || req.socket.remoteAddress || ''; }
function serveFile(req, res, url) { let p = url.pathname === '/' ? '/index.html' : url.pathname; if (!p.startsWith('/')) p = `/${p}`; const file = path.resolve(PUBLIC, `.${p}`); if (!file.startsWith(PUBLIC + path.sep) || !fs.existsSync(file) || !fs.statSync(file).isFile()) throw error(404, '页面不存在'); res.writeHead(200, { 'Content-Type': MIME[path.extname(file).toLowerCase()] || 'application/octet-stream', 'Content-Length': fs.statSync(file).size }); fs.createReadStream(file).pipe(res); }
function serveImageDir(req, res, url, dir) { const file = path.resolve(DATA, url.pathname.slice(1)); if (!file.startsWith(dir + path.sep) && file !== dir) throw error(404, '文件不存在'); if (!fs.existsSync(file) || !fs.statSync(file).isFile()) throw error(404, '文件不存在'); res.writeHead(200, { 'Content-Type': 'image/jpeg', 'Content-Length': fs.statSync(file).size, 'Cache-Control': 'public, max-age=86400' }); fs.createReadStream(file).pipe(res); }
// Fire-and-forget weather backfill: never blocks the upload response and
// never modifies the client's weather_text (stored separately).
function backfillRecordWeather(recordId) { const record = db.prepare('SELECT id, latitude, longitude, captured_at, weather_text FROM records WHERE id=?').get(recordId); if (!record) return; backfillWeather(record).then(r => { db.prepare("UPDATE records SET server_weather_text=?, server_weather_status='complete' WHERE id=?").run(r.text, record.id); }).catch(() => { db.prepare("UPDATE records SET server_weather_status='unavailable' WHERE id=?").run(record.id); }); }
function adminRecords(projectId) { return db.prepare(`SELECT r.*, t.sample_code, t.sample_type, t.planned_date, t.canceled_at, s.code site_code, s.name site_name, s.reference_image, s.instructions, s.risk_note, p.name project_name, p.code project_code, v.display_name villager_name, d.device_name, d.android_version FROM records r JOIN tasks t ON t.id=r.task_id JOIN sites s ON s.id=t.site_id JOIN projects p ON p.id=t.project_id JOIN villagers v ON v.id=t.villager_id LEFT JOIN devices d ON d.id=r.device_id WHERE t.project_id=? ORDER BY r.captured_at DESC, r.id`).all(projectId).map(r => ({ ...r, risk_flags: parse(r.risk_flags) })); }

// 诊断日志查询（管理员端）：按级别/设备/时间筛选，上限 5000 条。
function queryAppLogs(url) {
  const level = String(url.searchParams.get('level') || '');
  const deviceId = Number(url.searchParams.get('deviceId') || 0);
  const villagerId = Number(url.searchParams.get('villagerId') || 0);
  const from = String(url.searchParams.get('from') || '');
  const to = String(url.searchParams.get('to') || '');
  const limit = Math.min(Number(url.searchParams.get('limit') || 1000) || 1000, 5000);
  const cond = ['1=1'];
  const args = [];
  if (level) { cond.push('level=?'); args.push(level); }
  if (deviceId) { cond.push('device_id=?'); args.push(deviceId); }
  if (villagerId) { cond.push('villager_id=?'); args.push(villagerId); }
  if (from) { cond.push('created_at>=?'); args.push(`${from}T00:00:00`); }
  if (to) { cond.push('created_at<=?'); args.push(`${to}T23:59:59`); }
  args.push(limit);
  return db.prepare(`SELECT * FROM app_logs WHERE ${cond.join(' AND ')} ORDER BY id DESC LIMIT ?`).all(...args);
}

async function adminApi(req, res, url) {
  if (url.pathname === '/api/v1/admin/login' && req.method === 'POST') {
    const p = await body(req, 20_000);
    const key = `admin:${ipOf(req)}`;
    const limit = rateLimit.check(key, { max: 10, windowMs: 10 * 60_000 });
    if (limit.limited) throw error(429, `尝试过多，请${Math.ceil(limit.retryAfterMs / 60_000)}分钟后重试`);
    if (!safeEqual(p.password, config.adminPassword) || !verifyTotp(config.adminTotpSecret, p.totp)) {
      rateLimit.recordFailure(key, { max: 10, windowMs: 10 * 60_000 });
      throw error(401, '密码或动态验证码错误');
    }
    rateLimit.recordSuccess(key);
    audit(db, 'admin', 'admin', 'login', 'admin', null, {}, ipOf(req));
    return output(res, 200, { token: signToken(config.sessionSecret, 'admin', 'admin', {}, 43200) });
  }
  admin(req);
  if (url.pathname === '/api/v1/admin/bootstrap' && req.method === 'GET') return output(res, 200, { projects: db.prepare('SELECT * FROM projects ORDER BY id').all(), villagers: db.prepare('SELECT id,username,display_name,enabled FROM villagers').all(), summary: db.prepare("SELECT (SELECT COUNT(*) FROM tasks) tasks,(SELECT COUNT(*) FROM records) records,(SELECT COUNT(*) FROM records WHERE review_status='suspicious') suspicious").get(), publicBaseUrl: config.publicBaseUrl });
  if (url.pathname === '/api/v1/admin/health' && req.method === 'GET') { const s = fs.statfsSync(DATA); const free = Number(s.bfree) * Number(s.bsize); return output(res, 200, { freeBytes: free, warnLowDisk: free < 10 * 1024 ** 3, criticalLowDisk: free < 5 * 1024 ** 3, dataDir: DATA }); }
  if (url.pathname === '/api/v1/admin/projects' && req.method === 'POST') { const p = await body(req); try { const id = db.prepare('INSERT INTO projects(code,name,description,is_test,enabled) VALUES(?,?,?,?,1)').run(required(p.code, '项目编码'), required(p.name, '项目名称'), String(p.description || ''), p.isTest ? 1 : 0).lastInsertRowid; audit(db, 'admin', 'admin', 'create_project', 'project', id, { code: p.code }, ipOf(req)); return output(res, 201, { id }); } catch (e) { if (String(e.message).includes('UNIQUE')) throw error(422, '项目编码已存在'); throw e; } }
  let m = /^\/api\/v1\/admin\/projects\/(\d+)$/.exec(url.pathname);
  if (m && req.method === 'PUT') { const id = Number(m[1]), p = await body(req); if (!db.prepare('SELECT id FROM projects WHERE id=?').get(id)) throw error(404, '项目不存在'); try { db.prepare('UPDATE projects SET code=?,name=?,description=?,is_test=?,enabled=? WHERE id=?').run(required(p.code, '项目编码'), required(p.name, '项目名称'), String(p.description ?? ''), p.isTest ? 1 : 0, p.enabled == null ? 1 : (p.enabled ? 1 : 0), id); } catch (e) { if (String(e.message).includes('UNIQUE')) throw error(422, '项目编码已存在'); throw e; } audit(db, 'admin', 'admin', 'update_project', 'project', id, p, ipOf(req)); return output(res, 200, { ok: true }); }
  if (m && req.method === 'DELETE') { const id = Number(m[1]); if (!db.prepare('SELECT id FROM projects WHERE id=?').get(id)) throw error(404, '项目不存在'); if (db.prepare('SELECT id FROM tasks WHERE project_id=? LIMIT 1').get(id)) throw error(422, '项目已有任务数据，不能删除；可在编辑中停用'); transaction(() => { db.prepare('UPDATE sites SET deleted_at=CURRENT_TIMESTAMP WHERE project_id=?').run(id); db.prepare('DELETE FROM projects WHERE id=?').run(id); }); audit(db, 'admin', 'admin', 'delete_project', 'project', id, {}, ipOf(req)); return output(res, 200, { ok: true }); }
  if (url.pathname === '/api/v1/admin/sites' && req.method === 'GET') return output(res, 200, { sites: db.prepare('SELECT * FROM sites WHERE project_id=? AND deleted_at IS NULL ORDER BY sort_order').all(Number(url.searchParams.get('projectId') || 1)).map(s => ({ ...s, sample_types: parse(s.sample_types) })) });
  if (url.pathname === '/api/v1/admin/sites' && req.method === 'POST') { const p = await body(req); const id = db.prepare(`INSERT INTO sites(project_id,sort_order,code,name,latitude,longitude,altitude_m,sample_types,remarks,normal_radius_m,exception_radius_m,severe_radius_m,reference_image,instructions,risk_note,enabled) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(number(p.projectId, '项目'), Number(p.sortOrder || 0), required(p.code, '历史序号'), required(p.name, '点位名称'), number(p.latitude, '纬度'), number(p.longitude, '经度'), p.altitudeM == null ? null : Number(p.altitudeM), JSON.stringify(p.sampleTypes || []), String(p.remarks || ''), 30, 80, 300, String(p.referenceImage || ''), String(p.instructions || ''), String(p.riskNote || ''), p.enabled == null ? 1 : (p.enabled ? 1 : 0)).lastInsertRowid; audit(db, 'admin', 'admin', 'create_site', 'site', id, { code: p.code, projectId: p.projectId }, ipOf(req)); return output(res, 201, { id }); }
  m = /^\/api\/v1\/admin\/sites\/(\d+)$/.exec(url.pathname);
  if (m && req.method === 'PUT') { const id = Number(m[1]), p = await body(req), site = db.prepare('SELECT * FROM sites WHERE id=? AND deleted_at IS NULL').get(id); if (!site) throw error(404, '点位不存在'); try { db.prepare(`UPDATE sites SET sort_order=?,code=?,name=?,latitude=?,longitude=?,altitude_m=?,sample_types=?,remarks=?,normal_radius_m=?,exception_radius_m=?,severe_radius_m=?,reference_image=?,instructions=?,risk_note=?,enabled=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(Number(p.sortOrder ?? site.sort_order ?? 0), required(p.code, '历史序号'), required(p.name, '点位名称'), number(p.latitude, '纬度'), number(p.longitude, '经度'), p.altitudeM == null ? null : Number(p.altitudeM), JSON.stringify(p.sampleTypes || parse(site.sample_types)), String(p.remarks ?? ''), Number(p.normalRadiusM ?? site.normal_radius_m), Number(p.exceptionRadiusM ?? site.exception_radius_m), Number(p.severeRadiusM ?? site.severe_radius_m), String(p.referenceImage ?? site.reference_image ?? ''), String(p.instructions ?? ''), String(p.riskNote ?? ''), p.enabled == null ? site.enabled : (p.enabled ? 1 : 0), id); } catch (e) { if (String(e.message).includes('UNIQUE')) throw error(422, '该项目下历史序号已存在'); throw e; } audit(db, 'admin', 'admin', 'update_site', 'site', id, { before: site.code, after: p.code }, ipOf(req)); return output(res, 200, { ok: true }); }
  if (url.pathname === '/api/v1/admin/reference-images' && req.method === 'POST') { const p = await body(req, 12_000_000); const match = /^data:image\/(?:jpeg|jpg|png|webp);base64,([A-Za-z0-9+/=]+)$/.exec(String(p.imageData || '')); if (!match) throw error(422, '必须上传JPEG/PNG/WebP图片'); const image = Buffer.from(match[1], 'base64'); if (image.length < 100 || image.length > 10_000_000) throw error(413, '参考图无效或过大'); const name = `ref-${Date.now()}-${randomToken(4)}.jpg`, target = path.join(REFERENCE, name); await sharp(image).rotate().resize({ width: 1600, height: 1600, fit: 'inside', withoutEnlargement: true }).jpeg({ quality: 82 }).toFile(target); audit(db, 'admin', 'admin', 'upload_reference_image', 'reference', name, {}, ipOf(req)); return output(res, 201, { path: `/reference/${name}` }); }
  if (url.pathname === '/api/v1/admin/villagers' && req.method === 'POST') { const p = await body(req); try { const id = db.prepare('INSERT INTO villagers(username,display_name,pin_salt,pin_hash,enabled) VALUES(?,?,?,?,1)').run(required(p.username, '账号').toLowerCase().replace(/[^a-z0-9._-]/g, ''), required(p.displayName, '姓名'), '', '').lastInsertRowid; audit(db, 'admin', 'admin', 'create_villager', 'villager', id, { username: p.username }, ipOf(req)); return output(res, 201, { id }); } catch (e) { if (String(e.message).includes('UNIQUE')) throw error(422, '账号已存在'); throw e; } }
  m = /^\/api\/v1\/admin\/villagers\/(\d+)$/.exec(url.pathname);
  if (m && req.method === 'PUT') { const id = Number(m[1]), p = await body(req); if (!db.prepare('SELECT id FROM villagers WHERE id=?').get(id)) throw error(404, '采样员不存在'); const enabled = p.enabled == null ? 1 : (p.enabled ? 1 : 0); db.prepare('UPDATE villagers SET display_name=?,enabled=? WHERE id=?').run(required(p.displayName, '姓名'), enabled, id); db.prepare('UPDATE devices SET enabled=? WHERE villager_id=?').run(enabled, id); audit(db, 'admin', 'admin', 'update_villager', 'villager', id, p, ipOf(req)); return output(res, 200, { ok: true }); }
  if (m && req.method === 'DELETE') { const id = Number(m[1]); if (!db.prepare('SELECT id FROM villagers WHERE id=?').get(id)) throw error(404, '采样员不存在'); db.prepare('UPDATE villagers SET enabled=0 WHERE id=?').run(id); db.prepare('UPDATE devices SET enabled=0 WHERE villager_id=?').run(id); audit(db, 'admin', 'admin', 'disable_villager', 'villager', id, {}, ipOf(req)); return output(res, 200, { ok: true }); }
  m = /^\/api\/v1\/admin\/villagers\/(\d+)\/activation$/.exec(url.pathname);
  if (m && req.method === 'POST') { const user = db.prepare('SELECT * FROM villagers WHERE id=?').get(Number(m[1])); if (!user) throw error(404, '采样员不存在'); const raw = randomToken(24), hash = crypto.createHash('sha256').update(raw).digest('hex'), expires = new Date(Date.now() + 24 * 3600_000).toISOString(); db.prepare('INSERT INTO activation_codes(villager_id,token_hash,expires_at) VALUES(?,?,?)').run(user.id, hash, expires); const value = `BSC-ACT|${config.publicBaseUrl}|${user.username}|${raw}`; audit(db, 'admin', 'admin', 'create_activation', 'villager', user.id, { expiresAt: expires }, ipOf(req)); return output(res, 201, { value, qrDataUrl: await QRCode.toDataURL(value, { width: 480, margin: 1 }), expiresAt: expires }); }
  if (url.pathname === '/api/v1/admin/tasks' && req.method === 'POST') { const p = await body(req); const site = db.prepare('SELECT * FROM sites WHERE id=? AND enabled=1').get(number(p.siteId, '点位')); if (!site) throw error(422, '点位未启用'); const types = Array.isArray(p.sampleTypes) ? p.sampleTypes : [p.sampleType]; const created = transaction(() => types.map(type => { if (!['R','T','S','P','Y','L'].includes(type)) throw error(422, '样品类型无效'); const code = sampleCode(required(p.plannedDate, '日期'), type, site); return { id: Number(db.prepare(`INSERT INTO tasks(project_id,site_id,villager_id,planned_date,base_sample_code,sample_code,sample_type,sequence,qr_token) VALUES(?,?,?,?,?,?,?,?,?)`).run(site.project_id, site.id, number(p.villagerId, '采样员'), p.plannedDate, code.base, code.code, type, code.count, randomToken(24)).lastInsertRowid), sampleCode: code.code }; })); audit(db, 'admin', 'admin', 'create_tasks', 'site', site.id, { count: created.length, plannedDate: p.plannedDate, villagerId: p.villagerId }, ipOf(req)); return output(res, 201, { ids: created.map(c => c.id), codes: created.map(c => c.sampleCode) }); }
  if (url.pathname === '/api/v1/admin/tasks' && req.method === 'GET') { const project = Number(url.searchParams.get('projectId') || 1); const date = url.searchParams.get('date') || ''; const sql = `SELECT t.*,s.code site_code,s.name site_name,s.latitude target_latitude,s.longitude target_longitude,s.reference_image,s.instructions,s.risk_note,p.name project_name,p.code project_code,v.display_name villager_name,r.id record_id,r.captured_at,r.received_at,r.latitude,r.longitude,r.accuracy_m,r.distance_m,r.weather_text,r.server_weather_text,r.server_weather_status,r.manual_code,r.exception_category,r.exception_detail,r.mock_location,r.no_water,r.photo_path,r.photo_sha256,r.review_status,r.review_note,r.risk_flags,j.start_distance_m,j.interrupted,j.started_at FROM tasks t JOIN sites s ON s.id=t.site_id JOIN projects p ON p.id=t.project_id JOIN villagers v ON v.id=t.villager_id LEFT JOIN records r ON r.task_id=t.id AND r.is_primary=1 LEFT JOIN journeys j ON j.id=t.journey_id WHERE t.project_id=?${date === 'pending' ? " AND r.id IS NULL" : date ? " AND r.id IS NOT NULL AND substr(r.captured_at,1,10)=?" : ''} ORDER BY t.planned_date DESC,t.id`; const rows = date && date !== 'pending' ? db.prepare(sql).all(project, date) : db.prepare(sql).all(project); return output(res, 200, { tasks: rows.map(t => ({ ...t, risk_flags: parse(t.risk_flags), canceled_at: t.canceled_at || null, canceled_reason: t.canceled_reason || null })) }); }
  m = /^\/api\/v1\/admin\/tasks\/(\d+)\/cancel$/.exec(url.pathname);
  if (m && req.method === 'POST') { const id = Number(m[1]), p = await body(req), task = db.prepare('SELECT * FROM tasks WHERE id=?').get(id); if (!task) throw error(404, '任务不存在'); if (db.prepare('SELECT id FROM records WHERE task_id=? AND is_primary=1').get(id)) throw error(422, '已提交记录，不能取消；请使用退回重采'); if (task.canceled_at) throw error(422, '任务已取消'); db.prepare('UPDATE tasks SET canceled_at=CURRENT_TIMESTAMP,canceled_reason=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(String(p.reason || '管理员取消'), id); audit(db, 'admin', 'admin', 'cancel_task', 'task', id, { reason: p.reason }, ipOf(req)); return output(res, 200, { ok: true }); }
  m = /^\/api\/v1\/admin\/tasks\/(\d+)\/reschedule$/.exec(url.pathname);
  if (m && req.method === 'POST') { const id = Number(m[1]), p = await body(req), task = db.prepare('SELECT t.*,s.code site_code FROM tasks t JOIN sites s ON s.id=t.site_id WHERE t.id=?').get(id); if (!task) throw error(404, '任务不存在'); if (task.canceled_at) throw error(422, '任务已取消'); if (db.prepare('SELECT id FROM records WHERE task_id=? AND is_primary=1').get(id)) throw error(422, '已提交记录，不能改期'); const date = required(p.plannedDate, '日期'); const code = sampleCode(date, task.sample_type, { code: task.site_code, id: task.site_id }); transaction(() => { db.prepare('UPDATE tasks SET planned_date=?,base_sample_code=?,sample_code=?,sequence=?,qr_token=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(date, code.base, code.code, code.count, randomToken(24), id); }); audit(db, 'admin', 'admin', 'reschedule_task', 'task', id, { before: task.planned_date, after: date }, ipOf(req)); return output(res, 200, { sampleCode: code.code }); }
  m = /^\/api\/v1\/admin\/tasks\/(\d+)\/unlock$/.exec(url.pathname);
  if (m && req.method === 'POST') { const id = Number(m[1]); if (!db.prepare('SELECT id FROM tasks WHERE id=?').get(id)) throw error(404, '任务不存在'); db.prepare("UPDATE tasks SET locked_device_id=NULL,locked_at=NULL,journey_id=NULL,status='assigned',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(id); audit(db, 'admin', 'admin', 'unlock_task', 'task', id, {}, ipOf(req)); return output(res, 200, { ok: true }); }
  if (url.pathname === '/api/v1/admin/labels' && req.method === 'GET') { const ids = String(url.searchParams.get('taskIds') || '').split(',').map(Number).filter(Number.isFinite); if (!ids.length) throw error(400, '请选择任务'); const tasks = ids.map(id => db.prepare(`SELECT t.sample_code,t.qr_token,t.sample_type,t.planned_date,s.code site_code,p.code project_code FROM tasks t JOIN sites s ON s.id=t.site_id JOIN projects p ON p.id=t.project_id WHERE t.id=?`).get(id)).filter(Boolean); const withQr = []; for (const t of tasks) withQr.push({ ...t, qr_value: `BSC-SAMPLE|${t.sample_code}|${t.qr_token}`, qr_data_url: await QRCode.toDataURL(`BSC-SAMPLE|${t.sample_code}|${t.qr_token}`, { width: 240, margin: 1 }) }); const html = renderLabelPage(withQr); res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': Buffer.byteLength(html), 'Cache-Control': 'no-store' }); return res.end(html); }
  m = /^\/api\/v1\/admin\/records\/(\d+)\/review$/.exec(url.pathname);
  if (m && req.method === 'POST') { const p = await body(req); if (!['approved','rejected','suspicious','pending'].includes(p.status)) throw error(422, '审核状态无效'); db.prepare('UPDATE records SET review_status=?,review_note=? WHERE id=?').run(p.status, String(p.note || ''), Number(m[1])); audit(db, 'admin', 'admin', 'review', 'record', m[1], p, ipOf(req)); return output(res, 200, { ok: true }); }
  m = /^\/api\/v1\/admin\/records\/(\d+)\/backfill-weather$/.exec(url.pathname);
  if (m && req.method === 'POST') { const id = Number(m[1]), record = db.prepare('SELECT id,latitude,longitude,captured_at FROM records WHERE id=?').get(id); if (!record) throw error(404, '记录不存在'); const r = await backfillWeather(record); db.prepare('UPDATE records SET server_weather_text=?,server_weather_status=? WHERE id=?').run(r.text, r.status, id); audit(db, 'admin', 'admin', 'backfill_weather', 'record', id, { status: r.status }, ipOf(req)); return output(res, 200, { text: r.text, status: r.status }); }
  m = /^\/api\/v1\/admin\/journeys\/(\d+)\/track$/.exec(url.pathname);
  if (m && req.method === 'GET') { const journey = db.prepare('SELECT * FROM journeys WHERE id=?').get(Number(m[1])); if (!journey) throw error(404, '行程不存在'); return output(res, 200, { points: db.prepare('SELECT sequence,recorded_at,latitude,longitude,accuracy_m,speed_mps,mock_location FROM track_points WHERE journey_id=? ORDER BY sequence').all(journey.id) }); }
  if (url.pathname === '/api/v1/admin/logs' && req.method === 'GET') return output(res, 200, { logs: queryAppLogs(url) });
  m = /^\/api\/v1\/admin\/exports\/(csv|geojson|gpx|photos\.zip|audit\.csv|logs\.csv)$/.exec(url.pathname);
  if (m && req.method === 'GET') {
    const format = m[1], projectId = Number(url.searchParams.get('projectId') || 1);
    if (format === 'csv') { const bodyOut = Buffer.from(recordsCsv(adminRecords(projectId))); res.writeHead(200, { 'Content-Type': 'text/csv; charset=utf-8', 'Content-Length': bodyOut.length, 'Content-Disposition': 'attachment; filename="bsc-records.csv"' }); return res.end(bodyOut); }
    if (format === 'geojson') { const bodyOut = Buffer.from(recordsGeoJson(adminRecords(projectId))); res.writeHead(200, { 'Content-Type': 'application/geo+json; charset=utf-8', 'Content-Length': bodyOut.length, 'Content-Disposition': 'attachment; filename="bsc-records.geojson"' }); return res.end(bodyOut); }
    if (format === 'gpx') { const journeyId = Number(url.searchParams.get('journeyId') || 0); if (!journeyId) throw error(400, '请指定journeyId'); const journey = db.prepare('SELECT * FROM journeys WHERE id=?').get(journeyId); if (!journey) throw error(404, '行程不存在'); const points = db.prepare('SELECT recorded_at,latitude,longitude FROM track_points WHERE journey_id=? ORDER BY sequence').all(journeyId); const bodyOut = Buffer.from(gpx(points, `journey-${journeyId}`)); res.writeHead(200, { 'Content-Type': 'application/gpx+xml; charset=utf-8', 'Content-Length': bodyOut.length, 'Content-Disposition': `attachment; filename="journey-${journeyId}.gpx"` }); return res.end(bodyOut); }
    if (format === 'audit.csv') { const rows = db.prepare('SELECT * FROM audit_logs ORDER BY id').all().map(a => [a.id, a.actor_role, a.actor_id, a.action, a.entity_type, a.entity_id, a.details, a.ip_address, a.created_at]); const bodyOut = Buffer.from(`\uFEFFid,角色,操作者,动作,实体类型,实体ID,详情,IP,时间\r\n${rows.map(r => r.map(x => `"${String(x ?? '').replace(/"/g, '""')}"`).join(',')).join('\r\n')}\r\n`); res.writeHead(200, { 'Content-Type': 'text/csv; charset=utf-8', 'Content-Length': bodyOut.length, 'Content-Disposition': 'attachment; filename="bsc-audit.csv"' }); return res.end(bodyOut); }
    if (format === 'logs.csv') { const logs = queryAppLogs(url); const rows = logs.map(l => [l.id, l.created_at, l.client_created_at, l.level, l.villager_id, l.device_id, l.app_version, l.message, l.diagnostics]); const bodyOut = Buffer.from(`\uFEFFID,服务器接收时间,客户端时间,级别,采样员ID,设备ID,APP版本,消息,结构化详情\r\n${rows.map(r => r.map(x => `"${String(x ?? '').replace(/"/g, '""')}"`).join(',')).join('\r\n')}\r\n`); res.writeHead(200, { 'Content-Type': 'text/csv; charset=utf-8', 'Content-Length': bodyOut.length, 'Content-Disposition': 'attachment; filename="bsc-app-logs.csv"' }); return res.end(bodyOut); }
    const records = adminRecords(projectId); const entries = []; for (const r of records) { const file = path.join(DATA, r.photo_path.replace(/^\//, '')); if (!fs.existsSync(file)) continue; entries.push({ name: `${r.sample_code}-${r.id}.jpg`, data: fs.readFileSync(file), mtime: fs.statSync(file).mtime }); } const zip = zipStore(entries); res.writeHead(200, { 'Content-Type': 'application/zip', 'Content-Length': zip.length, 'Content-Disposition': 'attachment; filename="bsc-photos.zip"' }); return res.end(zip); }
  throw error(404, '管理员接口不存在');
}

function syncData(session) { expire(); const tasks = db.prepare(`SELECT t.*,p.name project_name,p.code project_code,s.code site_code,s.name site_name,s.latitude target_latitude,s.longitude target_longitude,s.normal_radius_m,s.exception_radius_m,s.severe_radius_m,s.reference_image,s.instructions,s.risk_note,s.remarks,r.id record_id,r.review_status,r.photo_path FROM tasks t JOIN projects p ON p.id=t.project_id JOIN sites s ON s.id=t.site_id LEFT JOIN records r ON r.task_id=t.id AND r.is_primary=1 WHERE t.villager_id=? AND p.enabled=1 AND s.deleted_at IS NULL ORDER BY CASE WHEN t.status IN('assigned','in_progress') THEN 0 ELSE 1 END,t.planned_date DESC,t.id`).all(session.villagerId).map(t => ({ ...t, canceled_at: t.canceled_at || null, canceled_reason: t.canceled_reason || null })); return { serverTime: new Date().toISOString(), tasks, rules: { normalRadiusM: 30, exceptionRadiusM: 80, severeRadiusM: 300, poorAccuracyM: 40, trackIntervalSeconds: 10, liveIntervalSeconds: 30 } }; }

async function mobileApi(req, res, url) {
  if (url.pathname === '/api/v1/mobile/activate' && req.method === 'POST') { const p = await body(req, 50_000), key = `mobile:${ipOf(req)}:${String(p.username || '').toLowerCase()}`; const lim = rateLimit.check(key); if (lim.limited) throw error(429, '尝试过多，请稍后再试'); const user = db.prepare('SELECT * FROM villagers WHERE username=? AND enabled=1').get(required(p.username, '账号').toLowerCase()); if (!user) { rateLimit.recordFailure(key); throw error(401, '账号不存在或已停用'); } const hash = crypto.createHash('sha256').update(required(p.activationToken, '激活码')).digest('hex'), act = db.prepare("SELECT * FROM activation_codes WHERE villager_id=? AND token_hash=? AND used_at IS NULL AND datetime(expires_at)>datetime('now')").get(user.id, hash); if (!act) { rateLimit.recordFailure(key); throw error(403, '激活二维码无效或已过期'); } rateLimit.recordSuccess(key); const device = transaction(() => { let d = db.prepare('SELECT id FROM devices WHERE villager_id=? AND device_uuid=?').get(user.id, required(p.deviceUuid, '设备编号')); let id; if (d) { id = d.id; db.prepare('UPDATE devices SET enabled=1,device_name=?,android_version=?,app_version=?,last_seen_at=CURRENT_TIMESTAMP WHERE id=?').run(String(p.deviceName || ''), String(p.androidVersion || ''), String(p.appVersion || ''), id); } else id = Number(db.prepare('INSERT INTO devices(villager_id,device_uuid,device_name,android_version,app_version,last_seen_at) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP)').run(user.id, p.deviceUuid, String(p.deviceName || ''), String(p.androidVersion || ''), String(p.appVersion || '')).lastInsertRowid); db.prepare('UPDATE activation_codes SET used_at=CURRENT_TIMESTAMP WHERE id=?').run(act.id); return id; }); audit(db, 'mobile', user.id, 'activate', 'device', device, { username: user.username }, ipOf(req)); return output(res, 200, { token: signToken(config.sessionSecret, 'villager', user.id, { deviceId: device }, 3650 * 86400), villager: { id: user.id, username: user.username, displayName: user.display_name }, deviceId: device }); }
  if (url.pathname === '/api/v1/mobile/login' && req.method === 'POST') { const p = await body(req, 30_000), key = `mobile:${ipOf(req)}:${String(p.username || '').toLowerCase()}`; const lim = rateLimit.check(key); if (lim.limited) throw error(429, '尝试过多，请稍后再试'); const user = db.prepare('SELECT * FROM villagers WHERE username=? AND enabled=1').get(String(p.username || '').toLowerCase()); if (!user) { rateLimit.recordFailure(key); throw error(401, '账号不存在或已停用'); } const d = db.prepare('SELECT * FROM devices WHERE villager_id=? AND device_uuid=? AND enabled=1').get(user.id, String(p.deviceUuid || '')); if (!d) throw error(403, '手机尚未激活'); rateLimit.recordSuccess(key); return output(res, 200, { token: signToken(config.sessionSecret, 'villager', user.id, { deviceId: d.id }, 3650 * 86400), villager: { id: user.id, username: user.username, displayName: user.display_name }, deviceId: d.id }); }
  const session = mobile(req); if (url.pathname === '/api/v1/mobile/sync' && req.method === 'GET') return output(res, 200, syncData(session));
  let m = /^\/api\/v1\/mobile\/tasks\/(\d+)\/start$/.exec(url.pathname);
  if (m && req.method === 'POST') { const id = Number(m[1]), p = await body(req); expire(); const task = db.prepare('SELECT t.*,s.latitude lat,s.longitude lon FROM tasks t JOIN sites s ON s.id=t.site_id WHERE t.id=? AND t.villager_id=?').get(id, session.villagerId); if (!task) throw error(404, '任务不存在'); if (task.locked_device_id && task.locked_device_id !== session.device.id) throw error(423, '任务已被另一台手机锁定'); const lat = number(p.latitude, '纬度'), lon = number(p.longitude, '经度'), acc = number(p.accuracyM ?? 9999, '精度'), startDistance = distance(lat, lon, task.lat, task.lon); const journey = transaction(() => { let j = db.prepare("SELECT * FROM journeys WHERE villager_id=? AND device_id=? AND site_id=? AND status='active' ORDER BY id DESC LIMIT 1").get(session.villagerId, session.device.id, task.site_id); if (!j) { const rid = db.prepare('INSERT INTO journeys(villager_id,device_id,site_id,started_at,start_latitude,start_longitude,start_accuracy_m,start_distance_m,weak_evidence) VALUES(?,?,?,CURRENT_TIMESTAMP,?,?,?,?,?)').run(session.villagerId, session.device.id, task.site_id, lat, lon, acc, startDistance, startDistance < 300 ? 1 : 0).lastInsertRowid; j = db.prepare('SELECT * FROM journeys WHERE id=?').get(rid); } db.prepare("UPDATE tasks SET locked_device_id=?,locked_at=CURRENT_TIMESTAMP,journey_id=?,status='in_progress' WHERE id=?").run(session.device.id, j.id, id); return j; }); return output(res, 200, { journey, startDistanceM: startDistance, weakEvidence: startDistance < 300 }); }
  m = /^\/api\/v1\/mobile\/journeys\/(\d+)\/track$/.exec(url.pathname);
  if (m && req.method === 'POST') { const id = Number(m[1]), j = db.prepare('SELECT * FROM journeys WHERE id=? AND villager_id=? AND device_id=?').get(id, session.villagerId, session.device.id); if (!j) throw error(404, '行程不存在'); const p = await body(req, 2_000_000), points = Array.isArray(p.points) ? p.points.slice(0, 1000) : [], add = db.prepare('INSERT OR IGNORE INTO track_points(journey_id,sequence,recorded_at,latitude,longitude,accuracy_m,speed_mps,mock_location) VALUES(?,?,?,?,?,?,?,?)'); transaction(() => points.forEach(x => add.run(id, Number(x.sequence), required(x.recordedAt, '轨迹时间'), number(x.latitude, '轨迹纬度'), number(x.longitude, '轨迹经度'), Number(x.accuracyM || 0), Number(x.speedMps || 0), x.mockLocation ? 1 : 0))); return output(res, 200, { inserted: points.length }); }
  m = /^\/api\/v1\/mobile\/tasks\/(\d+)\/live$/.exec(url.pathname);
  if (m && req.method === 'POST') { const id = Number(m[1]), p = await body(req, 30_000); db.prepare(`INSERT INTO live_locations(task_id,device_id,recorded_at,latitude,longitude,accuracy_m) VALUES(?,?,?,?,?,?) ON CONFLICT(task_id) DO UPDATE SET device_id=excluded.device_id,recorded_at=excluded.recorded_at,latitude=excluded.latitude,longitude=excluded.longitude,accuracy_m=excluded.accuracy_m`).run(id, session.device.id, required(p.recordedAt, '时间'), number(p.latitude, '纬度'), number(p.longitude, '经度'), Number(p.accuracyM || 0)); return output(res, 200, { ok: true }); }
  m = /^\/api\/v1\/mobile\/tasks\/(\d+)\/record$/.exec(url.pathname);
  if (m && req.method === 'POST') return saveRecord(req, res, session, Number(m[1]));
  m = /^\/api\/v1\/mobile\/journeys\/(\d+)\/complete$/.exec(url.pathname);
  if (m && req.method === 'POST') { db.prepare("UPDATE journeys SET status='completed',ended_at=CURRENT_TIMESTAMP WHERE id=? AND villager_id=? AND device_id=?").run(Number(m[1]), session.villagerId, session.device.id); return output(res, 200, { ok: true }); }
  m = /^\/api\/v1\/mobile\/journeys\/(\d+)\/interrupted$/.exec(url.pathname);
  if (m && req.method === 'POST') { const id = Number(m[1]); const j = db.prepare('SELECT id FROM journeys WHERE id=? AND villager_id=? AND device_id=?').get(id, session.villagerId, session.device.id); if (!j) throw error(404, '行程不存在'); db.prepare('UPDATE journeys SET interrupted=1 WHERE id=?').run(id); return output(res, 200, { ok: true }); }
  if (url.pathname === '/api/v1/mobile/logs' && req.method === 'POST') { const p = await body(req, 500_000), logs = Array.isArray(p.logs) ? p.logs.slice(0, 100) : [], add = db.prepare('INSERT INTO app_logs(villager_id,device_id,level,app_version,client_created_at,message,diagnostics) VALUES(?,?,?,?,?,?,?)'); transaction(() => logs.forEach(x => add.run(session.villagerId, session.device.id, String(x.level || 'error'), String(x.appVersion || ''), String(x.createdAt || ''), String(x.message || '').slice(0, 4000), JSON.stringify(x.diagnostics || {})))); return output(res, 201, { accepted: logs.length }); }
  throw error(404, '村民端接口不存在');
}

async function saveRecord(req, res, session, taskId) {
  const p = await body(req), client = required(p.clientRecordId, '本地记录编号'), duplicate = db.prepare('SELECT * FROM records WHERE client_record_id=?').get(client); if (duplicate) return output(res, 200, { id: duplicate.id, idempotent: true });
  const task = db.prepare(`SELECT t.*,s.code site_code,s.name site_name,s.latitude target_lat,s.longitude target_lon,s.normal_radius_m,s.exception_radius_m,s.severe_radius_m,pj.name project_name,j.weak_evidence,j.interrupted FROM tasks t JOIN sites s ON s.id=t.site_id JOIN projects pj ON pj.id=t.project_id LEFT JOIN journeys j ON j.id=t.journey_id WHERE t.id=? AND t.villager_id=?`).get(taskId, session.villagerId); if (!task) throw error(404, '任务不存在'); if (task.locked_device_id && task.locked_device_id !== session.device.id) throw error(423, '任务被另一台手机锁定');
  const lat = number(p.latitude, '纬度'), lon = number(p.longitude, '经度'), acc = number(p.accuracyM ?? 9999, '精度'), dist = distance(lat, lon, task.target_lat, task.target_lon); if (dist > task.severe_radius_m) throw error(422, `距离${Math.round(dist)}米，超过300米`); const noWater = Boolean(p.noWater), manual = Boolean(p.manualCode); if ((dist > task.normal_radius_m || noWater) && !String(p.exceptionCategory || '').trim()) throw error(422, '必须选择异常原因'); if (!noWater && !manual && !safeEqual(p.qrToken, task.qr_token)) throw error(422, '二维码不匹配'); if (manual && p.submittedCode !== task.sample_code) throw error(422, '手动编号不一致');
  const match = /^data:image\/(?:jpeg|jpg);base64,([A-Za-z0-9+/=]+)$/.exec(String(p.photoDataUrl || '')); if (!match) throw error(422, '必须上传现场相机JPEG'); const image = Buffer.from(match[1], 'base64'); if (image.length < 100 || image.length > 8_000_000) throw error(413, '照片大小无效');
  const risks = []; if (dist > task.exception_radius_m) risks.push('distance_80_300m'); else if (dist > task.normal_radius_m) risks.push('distance_30_80m'); if (acc > 40) risks.push('gps_accuracy_over_40m'); if (manual) risks.push('manual_bottle_code'); if (p.mockLocation) risks.push('mock_location'); if (p.offlineStart) risks.push('offline_start_lock_unverified'); if (task.weak_evidence) risks.push('weak_start_track'); if (task.interrupted) risks.push('track_interrupted'); if (String(p.capturedAt).slice(0, 10) !== task.planned_date) risks.push('late_sampling'); if (task.canceled_at) risks.push('task_canceled'); if (!p.weatherText || p.weatherText === '待补充') risks.push('weather_pending'); if (!db.prepare('SELECT COUNT(*) count FROM track_points WHERE journey_id=?').get(task.journey_id || -1).count) risks.push('missing_track'); const hash = crypto.createHash('sha256').update(image).digest('hex'); if (db.prepare('SELECT id FROM records WHERE photo_sha256=?').get(hash)) risks.push('duplicate_photo');
  const dir = path.join(UPLOADS, String(task.project_id)); fs.mkdirSync(dir, { recursive: true }); const file = `${task.sample_code}-${client.replace(/[^A-Za-z0-9_-]/g, '').slice(0, 40)}.jpg`, target = path.join(dir, file); await sharp(image).rotate().resize({ width: 2560, height: 2560, fit: 'inside', withoutEnlargement: true }).jpeg({ quality: 90 }).toFile(target);
  const existing = db.prepare('SELECT id FROM records WHERE task_id=? AND is_primary=1').get(taskId), primary = !existing; const id = transaction(() => { const rid = db.prepare(`INSERT INTO records(client_record_id,task_id,device_id,journey_id,is_primary,conflict_status,no_water,captured_at,latitude,longitude,accuracy_m,distance_m,weather_text,weather_status,exception_category,exception_detail,manual_code,mock_location,photo_path,photo_sha256,review_status,risk_flags) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(client, taskId, session.device.id, task.journey_id, primary ? 1 : 0, primary ? 'none' : 'needs_review', noWater ? 1 : 0, required(p.capturedAt, '拍照时间'), lat, lon, acc, dist, String(p.weatherText || '待补充'), p.weatherText && p.weatherText !== '待补充' ? 'complete' : 'pending', String(p.exceptionCategory || ''), String(p.exceptionDetail || ''), manual ? 1 : 0, p.mockLocation ? 1 : 0, `/uploads/${task.project_id}/${file}`, hash, risks.length ? 'suspicious' : 'pending', JSON.stringify([...new Set(risks)])).lastInsertRowid; if (primary) db.prepare("UPDATE tasks SET status='submitted',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(taskId); return Number(rid); });
  backfillRecordWeather(id);
  return output(res, 201, { id, primary, riskFlags: risks, severity: risks.some(x => ['distance_80_300m','manual_bottle_code','mock_location'].includes(x)) ? 'severe' : risks.length ? 'suspicious' : 'normal' });
}

const server = http.createServer(async (req, res) => { const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`); try { if (url.pathname === '/health') return output(res, 200, { status: 'healthy', version: '1.0.0', time: new Date().toISOString() }); if (url.pathname.startsWith('/api/v1/admin/')) return await adminApi(req, res, url); if (url.pathname.startsWith('/api/v1/mobile/')) return await mobileApi(req, res, url); if (url.pathname.startsWith('/uploads/')) return serveImageDir(req, res, url, UPLOADS); if (url.pathname.startsWith('/reference/')) return serveImageDir(req, res, url, REFERENCE); if (req.method === 'GET') return serveFile(req, res, url); throw error(404, '接口不存在'); } catch (e) { console.error(req.method, url.pathname, e); if (!res.headersSent) output(res, e.status || 500, { message: e.status ? e.message : '服务器内部错误' }); else res.destroy(); } });
const keepAlive = setInterval(() => rateLimit.prune(), 30 * 60_000);
keepAlive.unref?.();
server.listen(config.port, config.host, () => console.log(`BSC Sampling V1 listening on http://${config.host}:${config.port}`));
module.exports = server;
