package online.gpsgps.bscsampling;

import android.Manifest;import android.app.AlertDialog;import android.app.TimePickerDialog;import android.content.*;import android.content.pm.PackageManager;import android.database.Cursor;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.location.*;import android.net.*;import android.os.*;import android.provider.OpenableColumns;import android.view.*;import android.widget.*;import androidx.activity.result.*;import androidx.activity.result.contract.ActivityResultContracts;import androidx.annotation.NonNull;import androidx.appcompat.app.AppCompatActivity;import androidx.core.app.ActivityCompat;import androidx.core.content.ContextCompat;import com.google.android.material.button.MaterialButton;import org.json.JSONObject;import org.maplibre.android.MapLibre;import org.maplibre.android.annotations.*;import org.maplibre.android.camera.CameraPosition;import org.maplibre.android.geometry.LatLng;import org.maplibre.android.maps.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;

public final class MainActivity extends AppCompatActivity implements LocationListener{
 private FrameLayout content;private View tabs,header;private TextView title,status;private Prefs prefs;private Store db;private LocationManager lm;private Location here;private MapView mapView;private MapLibreMap map;private final Map<Long,Task> markerTasks=new HashMap<>();private final ExecutorService work=Executors.newSingleThreadExecutor();private QrData activation;private boolean unlocked;private ConnectivityManager.NetworkCallback netCallback;private int currentTab=1;private int taskFilter=0;private String mapDateFilter=null;private volatile boolean syncing=false;
 private final ActivityResultLauncher<Intent> scan=registerForActivityResult(new ActivityResultContracts.StartActivityForResult(),r->{if(r.getResultCode()!=RESULT_OK||r.getData()==null)return;try{activation=QrData.parse(r.getData().getStringExtra(ScanActivity.RESULT));if(!activation.activation)throw new IllegalArgumentException("请扫描设备激活二维码");showLogin();}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}});
 private final ActivityResultLauncher<String[]> permissions=registerForActivityResult(new ActivityResultContracts.RequestMultiplePermissions(),r->locations());
 private final ActivityResultLauncher<String> mapFile=registerForActivityResult(new ActivityResultContracts.GetContent(),this::importMap);
 protected void onCreate(Bundle b){super.onCreate(b);MapLibre.getInstance(this);setContentView(R.layout.activity_main);prefs=new Prefs(this);db=new Store(this);lm=getSystemService(LocationManager.class);content=findViewById(R.id.content);tabs=findViewById(R.id.tabs);header=findViewById(R.id.header);title=findViewById(R.id.title);status=findViewById(R.id.status);unlocked=prefs.activated();findViewById(R.id.tabMap).setOnClickListener(v->showMap());findViewById(R.id.tabTasks).setOnClickListener(v->showTasks());findViewById(R.id.tabUpload).setOnClickListener(v->showUpload());findViewById(R.id.tabMine).setOnClickListener(v->showMine());findViewById(R.id.sync).setOnClickListener(v->sync());netCallback=new ConnectivityManager.NetworkCallback(){public void onAvailable(@NonNull Network n){if(prefs.activated())runOnUiThread(()->{if(unlocked)sync();});}};try{getSystemService(ConnectivityManager.class).registerDefaultNetworkCallback(netCallback);}catch(Exception e){db.log("warning","NETCALLBACK "+e.getMessage());}showLogin();}
 private void showLogin(){
  destroyMap();tabs.setVisibility(View.GONE);findViewById(R.id.sync).setVisibility(View.GONE);content.removeAllViews();
  View v=getLayoutInflater().inflate(R.layout.view_login,content,false);content.addView(v);
  MaterialButton scanButton=v.findViewById(R.id.scanActivation),keyButton=v.findViewById(R.id.loginWithKey);
  EditText userInput=v.findViewById(R.id.activationUser),keyInput=v.findViewById(R.id.activationKey);TextView hint=v.findViewById(R.id.loginHint);
  v.findViewById(R.id.copyLog).setOnClickListener(x->copyLog());if(prefs.activated()){unlocked=true;enter();return;}unlocked=false;
  scanButton.setOnClickListener(x->scan.launch(new Intent(this,ScanActivity.class)));
  keyButton.setOnClickListener(x->{String user=userInput.getText().toString().trim().toLowerCase(Locale.ROOT),key=keyInput.getText().toString().trim();if(user.isEmpty()||key.isEmpty()){hint.setText("请输入采样员账号和激活密钥");return;}activateDevice(BuildConfig.DEFAULT_SERVER,user,key,scanButton,keyButton,hint);});
  if(activation!=null)activateDevice(activation.server,activation.user,activation.token,scanButton,keyButton,hint);else hint.setText("首次使用：扫描二维码，或输入管理员提供的账号和激活密钥\n每台手机只需激活一次");
 }
 private void activateDevice(String server,String user,String key,MaterialButton scanButton,MaterialButton keyButton,TextView hint){
  hint.setText("正在激活设备并登录…");scanButton.setEnabled(false);keyButton.setEnabled(false);
  work.execute(()->{try{JSONObject r=new Api(this).activate(server,user,key),u=r.getJSONObject("villager");prefs.save(server,r.getString("token"),u.getString("username"),u.getString("displayName"),r.getLong("deviceId"));unlocked=true;activation=null;runOnUiThread(this::enter);}catch(Exception e){db.log("error","ACTIVATE "+e.getMessage());runOnUiThread(()->{scanButton.setEnabled(true);keyButton.setEnabled(true);hint.setText("激活失败："+e.getMessage()+"\n请核对账号和一次性激活密钥");});}});
 }
 private void enter(){tabs.setVisibility(View.VISIBLE);findViewById(R.id.sync).setVisibility(View.VISIBLE);askPermissions();showMap();sync();String details="{}";try{details=new JSONObject().put("network",Util.networkType(this)).put("online",Util.online(this)).put("fineLocation",ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED).put("backgroundLocation",ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_BACKGROUND_LOCATION)==PackageManager.PERMISSION_GRANTED).put("camera",ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED).put("notifications",android.os.Build.VERSION.SDK_INT<33||ContextCompat.checkSelfPermission(this,Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED).put("pendingRecords",db.count("status!='uploaded'")).put("activeJourney",prefs.activeJourney()).toString();}catch(Exception ignored){}db.log("info","APP_READY",details);checkUpdate();}
 private void checkUpdate(){work.execute(()->{try{JSONObject v=new Api(MainActivity.this).version();String latest=v.optString("versionName","");boolean mandatory=v.optInt("mandatory",0)==1;if(!latest.isEmpty()&&!BuildConfig.VERSION_NAME.equals(latest)){String msg=(mandatory?"【必须更新】未更新前请勿继续采样。\n\n":"")+"当前版本 "+BuildConfig.VERSION_NAME+"，最新版本 "+latest+"。请让管理员安装新版本 APP。";runOnUiThread(()->new AlertDialog.Builder(MainActivity.this).setTitle((mandatory?"⚠ 必须更新 ":"发现新版本 ")+latest).setMessage(msg).setPositiveButton("知道了",null).setCancelable(!mandatory).show());}}catch(Exception ignored){}});}
 private void askPermissions(){List<String> x=new ArrayList<>();if(ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)x.add(Manifest.permission.ACCESS_FINE_LOCATION);if(Build.VERSION.SDK_INT>=33&&ContextCompat.checkSelfPermission(this,Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)x.add(Manifest.permission.POST_NOTIFICATIONS);if(x.isEmpty())locations();else permissions.launch(x.toArray(new String[0]));}
 private void locations(){if(ActivityCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return;try{lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,5000,0,this);if(lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER))lm.requestLocationUpdates(LocationManager.NETWORK_PROVIDER,5000,0,this);Location x=lm.getLastKnownLocation(LocationManager.GPS_PROVIDER);if(x!=null)onLocationChanged(x);}catch(Exception e){db.log("error","LOCATION "+e.getMessage());}}
 private void sync(){if(!unlocked)return;if(syncing){Toast.makeText(this,"同步正在进行中，请稍候…",Toast.LENGTH_SHORT).show();return;}syncing=true;status.setText(Util.online(this)?"正在同步服务器…":"当前离线，使用手机缓存");work.execute(()->{SyncEngine.Result r;try{if(Util.online(this))try{prefs.token(new Api(this).login().getString("token"));}catch(Exception e){db.log("warning","LOGIN_REFRESH "+e.getMessage());}r=new SyncEngine(this).run();}catch(Throwable t){db.log("error","SYNC_CRASH "+t.getClass().getSimpleName()+":"+t.getMessage());r=new SyncEngine.Result();r.message="同步异常，请查看诊断日志";}final SyncEngine.Result rr=r;final int taskCount=db.tasks().size();runOnUiThread(()->{syncing=false;status.setText(rr.message+" · 待上传"+db.count("status!='uploaded'")+"条");Toast.makeText(MainActivity.this,rr.message+"，任务 "+taskCount+" 个",Toast.LENGTH_SHORT).show();if(map!=null)markers();if(currentTab==1)showTasks();if(currentTab==2)showUpload();});});}
 private void showMap(){if(!unlocked)return;destroyMap();currentTab=0;title.setText("地图");content.removeAllViews();View v=getLayoutInflater().inflate(R.layout.view_map,content,false);content.addView(v);mapView=v.findViewById(R.id.map);mapView.onCreate(null);v.findViewById(R.id.locate).setOnClickListener(x->locate());if(mapDateFilter!=null){TextView f=new TextView(this);f.setText("仅显示 "+mapDateFilter+" 的点位（点此显示全部日期）");f.setTextColor(0xFFFFFFFF);f.setBackgroundColor(0xCC16A27A);int pad=(int)(10*getResources().getDisplayMetrics().density);f.setPadding(pad,pad,pad,pad);f.setGravity(android.view.Gravity.CENTER);f.setOnClickListener(x->{mapDateFilter=null;showMap();});FrameLayout root=(FrameLayout)v;FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT,FrameLayout.LayoutParams.WRAP_CONTENT,android.view.Gravity.TOP);root.addView(f,lp);}mapView.getMapAsync(m->{map=m;map.setStyle(new Style.Builder().fromJson(style()),s->{markers();center();});map.setOnMarkerClickListener(marker->{Task t=markerTasks.get(marker.getId());if(t!=null)startActivity(new Intent(this,TaskActivity.class).putExtra("task",t.id));return t!=null;});map.addOnMapClickListener(p->{copyCoords(p.getLatitude(),p.getLongitude());return true;});map.addOnMapLongClickListener(p->{new AlertDialog.Builder(this).setTitle("复制该位置坐标？").setMessage(String.format(Locale.CHINA,"【WGS84】%.8f°N，%.8f°E",p.getLatitude(),p.getLongitude())).setPositiveButton("复制",(d,w)->copyCoords(p.getLatitude(),p.getLongitude())).setNegativeButton("取消",null).show();return true;});});locationText();}
 private void locate(){if(map!=null&&here!=null)map.setCameraPosition(new CameraPosition.Builder().target(new LatLng(here.getLatitude(),here.getLongitude())).zoom(14).build());if(here==null){Toast.makeText(this,"正在获取WGS84位置…",Toast.LENGTH_SHORT).show();return;}new AlertDialog.Builder(this).setTitle("我的位置（WGS84）").setMessage(String.format(Locale.CHINA,"【WGS84】%.8f°N，%.8f°E\n精度 ±%.0fm",here.getLatitude(),here.getLongitude(),here.getAccuracy())).setPositiveButton("复制",(d,w)->copyCoords(here.getLatitude(),here.getLongitude())).setNegativeButton("关闭",null).show();}
 private void copyCoords(double lat,double lon){String s=String.format(Locale.CHINA,"【WGS84】%.8f°N，%.8f°E",lat,lon);getSystemService(android.content.ClipboardManager.class).setPrimaryClip(ClipData.newPlainText("WGS84坐标",s));Toast.makeText(this,"已复制 "+s,Toast.LENGTH_LONG).show();}
 // 采样点标记：水滴轮廓 + 历史序号文字，自动常显编号（绿=已采样 灰=已取消 蓝=进行中 橙=待采样）。
 private Icon markerIcon(String label,int color){int w=120,h=150;Bitmap b=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);Paint fill=new Paint(Paint.ANTI_ALIAS_FLAG);fill.setColor(color);Paint border=new Paint(Paint.ANTI_ALIAS_FLAG);border.setStyle(Paint.Style.STROKE);border.setStrokeWidth(8);border.setColor(0xFFFFFFFF);Path p=new Path();float cx=w/2f;p.moveTo(cx,8);p.cubicTo(cx+46,44,cx+42,100,cx,h-16);p.cubicTo(cx-42,100,cx-46,44,cx,8);p.close();c.drawPath(p,fill);c.drawPath(p,border);Paint text=new Paint(Paint.ANTI_ALIAS_FLAG);text.setColor(0xFFFFFFFF);text.setTextSize(40);text.setFakeBoldText(true);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(MarkerLayout.fitTextSize(40f,24f,84f,text.measureText(label)));c.drawText(label,cx,82,text);return IconFactory.getInstance(this).fromBitmap(b);}
 private String style(){String f=prefs.map();if(!f.isEmpty()&&new File(f).isFile())return"{\"version\":8,\"sources\":{\"s\":{\"type\":\"raster\",\"url\":\"mbtiles://"+f.replace("\\","/").replace(" ","%20")+"\",\"tileSize\":256}},\"layers\":[{\"id\":\"s\",\"type\":\"raster\",\"source\":\"s\"}]}";return"{\"version\":8,\"sources\":{\"s\":{\"type\":\"raster\",\"tiles\":[\"https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}\"],\"tileSize\":256,\"maxzoom\":17}},\"layers\":[{\"id\":\"s\",\"type\":\"raster\",\"source\":\"s\"}]}";}
 private void markers(){if(map==null||map.getStyle()==null)return;map.clear();markerTasks.clear();Map<String,List<Task>> groups=new LinkedHashMap<>();for(Task t:db.tasks()){if(t.canceled())continue;if(mapDateFilter!=null&&!mapDateFilter.equals(t.j.optString("planned_date","未定日期")))continue;long siteId=t.j.optLong("site_id");String key=siteId>0?"site:"+siteId:String.format(Locale.ROOT,"coord:%.7f:%.7f",t.lat(),t.lon());groups.computeIfAbsent(key,k->new ArrayList<>()).add(t);}for(List<Task> group:groups.values()){for(int index=0;index<group.size();index++){Task t=group.get(index);MarkerLayout.Position position=MarkerLayout.spread(t.lat(),t.lon(),index,group.size());int color=t.submitted()?0xFF16A27A:0xFFEF9C2F;String prefix=t.submitted()?"✓ ":"待采样 ";String count=group.size()>1?" ×"+group.size():"";Marker m=map.addMarker(new MarkerOptions().position(new LatLng(position.latitude,position.longitude)).icon(markerIcon(t.siteCode(),color)).title(prefix+t.title()+count).snippet(t.code()));markerTasks.put(m.getId(),t);}}if(here!=null)map.addMarker(new MarkerOptions().position(new LatLng(here.getLatitude(),here.getLongitude())).title("我的位置（WGS84）"));}
 protected void onNewIntent(Intent i){super.onNewIntent(i);if(prefs.activated()&&unlocked)showMap();}
 private void center(){if(map!=null&&here!=null)map.setCameraPosition(new CameraPosition.Builder().target(new LatLng(here.getLatitude(),here.getLongitude())).zoom(14).build());}
 private void legacyShowTasks(){if(!unlocked)return;destroyMap();currentTab=1;title.setText("我的任务");content.removeAllViews();View v=getLayoutInflater().inflate(R.layout.view_list,content,false);content.addView(v);List<Task> all=new ArrayList<>(db.tasks());List<Task> a=new ArrayList<>();for(Task t:all){if(t.canceled())continue;boolean sub=t.submitted();if(taskFilter==1&&sub)continue;if(taskFilter==2&&!sub)continue;a.add(t);}
  // 筛选条：全部/待采样/已采样（按需求只保留两种状态，已取消不再显示）
  LinearLayout chips=new LinearLayout(this);chips.setOrientation(LinearLayout.HORIZONTAL);chips.setPadding(0,10,0,0);String[] names={"全部","待采样","已采样"};for(int i=0;i<3;i++){final int fi=i;MaterialButton b=new MaterialButton(this);b.setText(names[i]);b.setMinWidth(0);b.setPadding(24,0,24,0);b.setTextSize(14);b.setBackgroundColor(taskFilter==fi?0xFF16A27A:0xFFE3EDEB);b.setTextColor(taskFilter==fi?0xFFFFFFFF:0xFF17343A);b.setOnClickListener(x->{taskFilter=fi;showTasks();});chips.addView(b);}((LinearLayout)v).addView(chips,1);
  java.util.Map<String,List<Task>> groups=new java.util.TreeMap<>();for(Task t:a)groups.computeIfAbsent(t.j.optString("planned_date","未定日期"),k->new ArrayList<>()).add(t);java.util.Comparator<Task> byDist=(x,y)->Double.compare(here==null?x.id:Util.distance(here.getLatitude(),here.getLongitude(),x.lat(),x.lon()),here==null?y.id:Util.distance(here.getLatitude(),here.getLongitude(),y.lat(),y.lon()));List<String> dates=new ArrayList<>(groups.keySet());Collections.sort(dates,Comparator.reverseOrder());List<List<Task>> data=new ArrayList<>();for(String d:dates){List<Task> l=groups.get(d);l.sort(byDist);data.add(l);}((TextView)v.findViewById(R.id.listHint)).setText(a.isEmpty()?"暂无任务。请联网后点右上角同步；若同步后仍为空，请让管理员确认下发任务的采样员是本账号（"+prefs.user()+"）。":"按日期归档 · 共"+a.size()+"个任务（默认展开，最新日期在前）");ExpandableListView list=v.findViewById(R.id.list);list.setAdapter(new DateAdapter(dates,data));for(int i=0;i<dates.size();i++)list.expandGroup(i);list.setOnGroupClickListener((p,x,g,id)->{mapDateFilter=dates.get(g);return false;});list.setOnChildClickListener((p,x,g,c,id)->{startActivity(new Intent(this,TaskActivity.class).putExtra("task",data.get(g).get(c).id));return true;});}
 private int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+0.5f);}
 private GradientDrawable shape(int color,float radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
 private TextView smallBadge(String value,int color){TextView v=new TextView(this);v.setText(value);v.setTextSize(11);v.setTextColor(color);v.setTypeface(null,android.graphics.Typeface.BOLD);v.setPadding(dp(6),dp(3),dp(6),dp(3));v.setBackground(shape(0xFFE4F3EF,14));return v;}
 private void showTasks(){if(!unlocked)return;destroyMap();currentTab=1;title.setText("我的任务");content.removeAllViews();View root=getLayoutInflater().inflate(R.layout.view_list,content,false);content.addView(root);LinearLayout datesView=root.findViewById(R.id.dateTaskList),pointsView=root.findViewById(R.id.pointList);TextView pointTitle=root.findViewById(R.id.pointPanelTitle),pointSummary=root.findViewById(R.id.pointPanelSummary);List<Task> visible=new ArrayList<>();for(Task t:db.tasks())if(!t.canceled())visible.add(t);java.util.Map<String,List<Task>> groups=new java.util.TreeMap<>(Comparator.reverseOrder());for(Task t:visible)groups.computeIfAbsent(t.plannedDate(),k->new ArrayList<>()).add(t);List<String> dates=new ArrayList<>(groups.keySet());if(dates.isEmpty()){datesView.addView(emptyText("暂无下发任务\n请联网后点击右上角同步"));pointTitle.setText("暂无日期任务");pointSummary.setText("");return;}for(List<Task> list:groups.values())list.sort(Comparator.comparing(Task::code));final String first=dates.get(0);for(String date:dates){List<Task> list=groups.get(date);int done=0;for(Task t:list)if(t.submitted())done++;LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(9),dp(9),dp(7),dp(9));card.setBackground(shape(date.equals(first)?0xFFDDF3ED:0xFFFFFFFF,12));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,LinearLayout.LayoutParams.WRAP_CONTENT);cp.setMargins(0,0,0,dp(8));card.setLayoutParams(cp);TextView d=new TextView(this);d.setText(date);d.setTextSize(15);d.setTypeface(null,android.graphics.Typeface.BOLD);d.setTextColor(0xFF09262B);card.addView(d);LinearLayout stats=new LinearLayout(this);stats.setOrientation(LinearLayout.HORIZONTAL);TextView ok=smallBadge("已采 "+done,0xFF087A64);TextView pending=smallBadge("未采 "+(list.size()-done),0xFFD06A00);stats.addView(ok);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-2,-2);pp.setMargins(dp(4),0,0,0);stats.addView(pending,pp);card.addView(stats);card.setOnClickListener(v->{mapDateFilter=date;renderPointsForDate(date,groups,pointsView,pointTitle,pointSummary);for(int i=0;i<datesView.getChildCount();i++){View x=datesView.getChildAt(i);if(x instanceof LinearLayout)x.setBackground(shape(x==card?0xFFDDF3ED:0xFFFFFFFF,12));}});datesView.addView(card);}renderPointsForDate(first,groups,pointsView,pointTitle,pointSummary);}
 private TextView emptyText(String s){TextView v=new TextView(this);v.setText(s);v.setTextSize(15);v.setTextColor(0xFF55706D);v.setGravity(Gravity.CENTER);v.setPadding(dp(12),dp(40),dp(12),dp(40));return v;}
 private void renderPointsForDate(String date,java.util.Map<String,List<Task>> groups,LinearLayout out,TextView titleView,TextView summary){out.removeAllViews();List<Task> list=groups.get(date);if(list==null||list.isEmpty()){titleView.setText(date);summary.setText("暂无采样点");return;}int done=0;for(Task t:list)if(t.submitted())done++;titleView.setText(date);summary.setText("采样点 "+list.size()+" · 已完成 "+done+" · 待采样 "+(list.size()-done));for(Task t:list){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.HORIZONTAL);card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(8),dp(8),dp(6),dp(8));card.setBackground(shape(0xFFFFFFFF,12));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,LinearLayout.LayoutParams.WRAP_CONTENT);cp.setMargins(0,0,0,dp(8));card.setLayoutParams(cp);TextView pin=new TextView(this);pin.setText("●");pin.setTextSize(20);pin.setTextColor(0xFF087A64);pin.setGravity(Gravity.CENTER);card.addView(pin,new LinearLayout.LayoutParams(dp(28),dp(40)));LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);info.setPadding(dp(5),0,dp(2),0);TextView code=new TextView(this);code.setText(t.code());code.setTextSize(14);code.setTypeface(null,android.graphics.Typeface.BOLD);code.setTextColor(0xFF09262B);info.addView(code);TextView meta=new TextView(this);String time=t.plannedTime().isEmpty()?"计划时间 未设置":"计划 "+t.plannedTime()+" ✎";meta.setText(Util.type(t.j.optString("sample_type"))+" · "+time);meta.setTextSize(11);meta.setTextColor(0xFF55706D);info.addView(meta);TextView owner=new TextView(this);owner.setText(t.statusLabel()+" · "+t.villagerName()+" · "+t.deviceName());owner.setTextSize(11);owner.setTextColor(t.submitted()?0xFF087A64:0xFFD06A00);info.addView(owner);card.addView(info,new LinearLayout.LayoutParams(0,-2,1));TextView arrow=new TextView(this);arrow.setText("›");arrow.setTextSize(28);arrow.setTextColor(0xFF6B7C7A);card.addView(arrow,new LinearLayout.LayoutParams(dp(24),dp(48)));TextView timeEditor=meta;timeEditor.setOnClickListener(v->editPlannedTime(t,timeEditor));card.setOnClickListener(v->startActivity(new Intent(this,TaskActivity.class).putExtra("task",t.id)));out.addView(card);}}
 private void editPlannedTime(Task t,TextView label){if(t.submitted()){Toast.makeText(this,"已采样任务不能修改计划时间",Toast.LENGTH_SHORT).show();return;}int hour=9,minute=0;try{if(!t.plannedTime().isEmpty()){String[] p=t.plannedTime().split(":");hour=Integer.parseInt(p[0]);minute=Integer.parseInt(p[1]);}}catch(Exception ignored){}new TimePickerDialog(this,(v,h,m)->{String value=String.format(Locale.CHINA,"%02d:%02d",h,m);db.setPlannedTime(t.id,value);label.setText(Util.type(t.j.optString("sample_type"))+" · 计划 "+value+" ✎");androidx.work.WorkManager.getInstance(this).enqueue(new androidx.work.OneTimeWorkRequest.Builder(SyncWorker.class).setConstraints(new androidx.work.Constraints.Builder().setRequiredNetworkType(androidx.work.NetworkType.CONNECTED).build()).build());work.execute(()->{try{if(!Util.online(this))throw new IOException("离线");new Api(this).schedule(t.id,value);db.scheduleDone(t.id);runOnUiThread(()->Toast.makeText(this,"计划时间已保存",Toast.LENGTH_SHORT).show());}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"已保存到手机，联网后自动同步",Toast.LENGTH_SHORT).show());}});},hour,minute,true).show();}
 private void showUpload(){if(!unlocked)return;destroyMap();currentTab=2;title.setText("上传");LinearLayout p=panel();int pending=db.count("status!='uploaded'"),done=db.count("status='uploaded'");text(p,"待同步 "+pending+" 条 · 已同步 "+done+" 条",22);text(p,"有网络时自动同步；未同步的数据会一直保存在手机，不会丢失。",15);for(JSONObject r:db.recordsAll()){Task t=db.task(r.optLong("taskId"));String code=t==null?("任务"+r.optLong("taskId")):t.code();if(r.optString("status").equals("uploaded")){String at=r.optString("uploadedAt").replace('T',' ');if(at.length()>16)at=at.substring(0,16);text(p,"✅ 已同步 "+code+"　"+at,15);}else{String err=r.optString("error");if(err.length()>90)err=err.substring(0,90)+"…";text(p,"⏳ 未同步 "+code+(err.isEmpty()?"　等待上传":"　上次失败："+err),15);}}MaterialButton b=button("立即重试同步");b.setOnClickListener(v->{sync();showUpload();});p.addView(b);content.removeAllViews();content.addView(p);}
 private void showMine(){if(!unlocked)return;destroyMap();currentTab=3;title.setText("我的");LinearLayout p=panel();text(p,prefs.name()+"（"+prefs.user()+"）",22);text(p,"服务器："+prefs.server()+"\n设备："+Util.uuid(this)+"\n坐标：WGS84\n版本："+BuildConfig.VERSION_NAME,16);MaterialButton map=button(prefs.map().isEmpty()?"导入离线卫星地图包（MBTiles）":"更换离线地图包");map.setOnClickListener(v->mapFile.launch("*/*"));p.addView(map);MaterialButton log=button("复制诊断日志");log.setOnClickListener(v->copyLog());p.addView(log);MaterialButton csv=button("分享日志文件（Excel可打开）");csv.setOnClickListener(v->{java.io.File f=db.logsCsv();if(f==null){Toast.makeText(this,"生成日志文件失败",Toast.LENGTH_LONG).show();return;}try{android.net.Uri u=androidx.core.content.FileProvider.getUriForFile(this,"online.gpsgps.bscsampling.files",f);Intent s=new Intent(Intent.ACTION_SEND).setType("text/csv").putExtra(Intent.EXTRA_STREAM,u).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(s,"分享日志文件"));}catch(Exception e){Toast.makeText(this,"分享失败："+e.getMessage(),Toast.LENGTH_LONG).show();}});p.addView(csv);content.removeAllViews();content.addView(p);}
 private LinearLayout panel(){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(24,24,24,24);return p;}private void text(LinearLayout p,String s,int size){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(Color.DKGRAY);v.setPadding(10,16,10,16);p.addView(v);}private MaterialButton button(String s){MaterialButton b=new MaterialButton(this);b.setText(s);b.setTextSize(18);b.setMinHeight(64);return b;}
 private void importMap(Uri u){if(u==null)return;work.execute(()->{try{long declared=-1;try(Cursor c=getContentResolver().query(u,new String[]{OpenableColumns.SIZE},null,null,null)){if(c!=null&&c.moveToFirst())declared=c.getLong(0);}if(declared>2_000_000_000L)throw new IOException("地图包超过2GB");File out=new File(getFilesDir(),"basongcuo.mbtiles");try(InputStream in=getContentResolver().openInputStream(u);FileOutputStream o=new FileOutputStream(out)){byte[] b=new byte[1024*1024];int n;long total=0;while((n=in.read(b))>=0){total+=n;if(total>2_000_000_000L)throw new IOException("地图包超过2GB");o.write(b,0,n);}}byte[] h=new byte[16];try(FileInputStream in=new FileInputStream(out)){if(in.read(h)!=16||!new String(h,StandardCharsets.US_ASCII).startsWith("SQLite format 3"))throw new IOException("不是有效MBTiles地图包");}prefs.map(out.getPath());runOnUiThread(()->Toast.makeText(this,"离线地图导入成功",Toast.LENGTH_LONG).show());}catch(Exception e){db.log("error","MAP_IMPORT "+e.getMessage());runOnUiThread(()->Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show());}});}
 private void copyLog(){getSystemService(android.content.ClipboardManager.class).setPrimaryClip(ClipData.newPlainText("巴松措采样日志",db.diagnostics()));Toast.makeText(this,"日志已复制，可以发给管理员",Toast.LENGTH_LONG).show();}
 public void onLocationChanged(@NonNull Location l){here=l;locationText();if(map!=null)markers();}private void locationText(){TextView v=content.findViewById(R.id.location);if(v!=null)v.setText(here==null?"正在获取WGS84位置…":String.format(Locale.CHINA,"WGS84 %.6f, %.6f　精度±%.0fm",here.getLatitude(),here.getLongitude(),here.getAccuracy()));}
 private void destroyMap(){if(mapView!=null){mapView.onStop();mapView.onDestroy();mapView=null;map=null;}}
 protected void onStart(){super.onStart();if(mapView!=null)mapView.onStart();}protected void onResume(){super.onResume();if(mapView!=null)mapView.onResume();}protected void onPause(){if(mapView!=null)mapView.onPause();super.onPause();}protected void onStop(){if(mapView!=null)mapView.onStop();super.onStop();}public void onLowMemory(){super.onLowMemory();if(mapView!=null)mapView.onLowMemory();}protected void onDestroy(){try{lm.removeUpdates(this);}catch(Exception ignored){}try{if(netCallback!=null)getSystemService(ConnectivityManager.class).unregisterNetworkCallback(netCallback);}catch(Exception ignored){}destroyMap();work.shutdown();super.onDestroy();}
 private final class DateAdapter extends BaseExpandableListAdapter{private final List<String> dates;private final List<List<Task>> groups;DateAdapter(List<String> d,List<List<Task>> g){dates=d;groups=g;}public int getGroupCount(){return dates.size();}public int getChildrenCount(int i){return groups.get(i).size();}public Object getGroup(int i){return dates.get(i);}public Object getChild(int i,int j){return groups.get(i).get(j);}public long getGroupId(int i){return -i-1;}public long getChildId(int i,int j){return groups.get(i).get(j).id;}public boolean hasStableIds(){return true;}public boolean isChildSelectable(int i,int j){return true;}public View getGroupView(int i,boolean expanded,View v,ViewGroup p){if(v==null){v=new TextView(MainActivity.this);int pad=(int)(14*getResources().getDisplayMetrics().density);v.setPadding(pad,pad,pad,pad);((TextView)v).setTextSize(18);((TextView)v).setBackgroundResource(R.drawable.card);}int pending=0;for(Task t:groups.get(i))if(!t.submitted())pending++;( (TextView)v).setText(dates.get(i)+"　"+(expanded?"▾":"▸")+"　"+groups.get(i).size()+" 个任务 · 待采样 "+pending);((TextView)v).setTypeface(null,android.graphics.Typeface.BOLD);((TextView)v).setTextColor(0xFF17343A);return v;}public View getChildView(int i,int j,boolean last,View v,ViewGroup p){if(v==null)v=getLayoutInflater().inflate(R.layout.item_task,p,false);Task t=groups.get(i).get(j);((TextView)v.findViewById(R.id.itemTitle)).setText(t.title()+" · 历史"+t.siteCode());((TextView)v.findViewById(R.id.itemCode)).setText(t.code());double d=here==null?-1:Util.distance(here.getLatitude(),here.getLongitude(),t.lat(),t.lon());((TextView)v.findViewById(R.id.itemMeta)).setText(Util.type(t.j.optString("sample_type"))+" · "+(d<0?"距离未知":d<1000?Math.round(d)+"米":String.format(Locale.CHINA,"%.1f公里",d/1000)));TextView st=v.findViewById(R.id.itemStatus);boolean sub=t.submitted(),can=t.canceled();st.setText(sub?"已采样":can?"已取消":"待采样");st.setTextColor(sub?0xFF087557:can?0xFF777F7E:0xFFB3402F);st.setTypeface(null,android.graphics.Typeface.BOLD);v.getBackground().setTint(sub?0xFFE3F5EC:can?0xFFF0F1F1:0xFFFDECEC);return v;}}
}
