package online.gpsgps.bscsampling;

import android.Manifest;import android.app.AlertDialog;import android.app.TimePickerDialog;import android.content.*;import android.content.pm.PackageManager;import android.database.Cursor;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.location.*;import android.net.*;import android.os.*;import android.provider.OpenableColumns;import android.view.*;import android.widget.*;import androidx.activity.result.*;import androidx.activity.result.contract.ActivityResultContracts;import androidx.annotation.NonNull;import androidx.appcompat.app.AppCompatActivity;import androidx.core.app.ActivityCompat;import androidx.core.content.ContextCompat;import com.google.android.material.button.MaterialButton;import org.json.JSONObject;import org.maplibre.android.MapLibre;import org.maplibre.android.annotations.*;import org.maplibre.android.camera.CameraPosition;import org.maplibre.android.geometry.LatLng;import org.maplibre.android.maps.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;

public final class MainActivity extends AppCompatActivity implements LocationListener{
 private FrameLayout content;private View tabs,header;private TextView title,status;private Prefs prefs;private Store db;private LocationManager lm;private Location here;private MapView mapView;private MapLibreMap map;private final Map<Long,Task> markerTasks=new HashMap<>();private final ExecutorService work=Executors.newSingleThreadExecutor();private QrData activation;private boolean unlocked;private ConnectivityManager.NetworkCallback netCallback;private int currentTab=1;private int taskFilter=0;private String mapDateFilter=null;private volatile boolean syncing=false;
 private final ActivityResultLauncher<Intent> scan=registerForActivityResult(new ActivityResultContracts.StartActivityForResult(),r->{if(r.getResultCode()!=RESULT_OK||r.getData()==null)return;try{activation=QrData.parse(r.getData().getStringExtra(ScanActivity.RESULT));if(!activation.activation)throw new IllegalArgumentException("请扫描设备激活二维码");showLogin();}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}});
 private final ActivityResultLauncher<String[]> permissions=registerForActivityResult(new ActivityResultContracts.RequestMultiplePermissions(),r->locations());
 private final ActivityResultLauncher<String> mapFile=registerForActivityResult(new ActivityResultContracts.GetContent(),this::importMap);
 protected void onCreate(Bundle b){super.onCreate(b);MapLibre.getInstance(this);setContentView(R.layout.activity_main);prefs=new Prefs(this);db=new Store(this);lm=getSystemService(LocationManager.class);content=findViewById(R.id.content);tabs=findViewById(R.id.tabs);header=findViewById(R.id.header);title=findViewById(R.id.title);status=findViewById(R.id.status);setupMainIcons();unlocked=prefs.activated();findViewById(R.id.tabMap).setOnClickListener(v->showMap());findViewById(R.id.tabTasks).setOnClickListener(v->showTasks());findViewById(R.id.tabUpload).setOnClickListener(v->showUpload());findViewById(R.id.tabMine).setOnClickListener(v->showMine());findViewById(R.id.sync).setOnClickListener(v->sync());netCallback=new ConnectivityManager.NetworkCallback(){public void onAvailable(@NonNull Network n){if(prefs.activated())runOnUiThread(()->{if(unlocked)sync();});}};try{getSystemService(ConnectivityManager.class).registerDefaultNetworkCallback(netCallback);}catch(Exception e){db.log("warning","NETCALLBACK "+e.getMessage());}showLogin();}
 private void setupMainIcons(){setIcon(findViewById(R.id.tabMap),"map",0xFF087A64);setIcon(findViewById(R.id.tabTasks),"assignment",0xFF087A64);setIcon(findViewById(R.id.tabUpload),"cloud_upload",0xFF087A64);setIcon(findViewById(R.id.tabMine),"person",0xFF087A64);setIcon(findViewById(R.id.sync),"sync",0xFFFFFFFF);}
 private void selectTab(int selected){int[] ids={R.id.tabMap,R.id.tabTasks,R.id.tabUpload,R.id.tabMine};String[] icons={"map","assignment","cloud_upload","person"};for(int i=0;i<ids.length;i++){MaterialButton button=findViewById(ids[i]);boolean active=i==selected;int color=active?0xFF087A64:0xFF5B6966;button.setTextColor(color);button.setBackgroundTintList(android.content.res.ColorStateList.valueOf(active?0xFFE0F3ED:0x00000000));setIcon(button,icons[i],color);}}
 private void setIcon(MaterialButton button,String name,int color){button.setIcon(MaterialSymbols.drawable(name,color));button.setIconTint(null);button.setIconSize(dp(24));button.setIconPadding(dp(6));}
 private ImageView symbol(String name,int color,int size){ImageView image=new ImageView(this);image.setImageDrawable(MaterialSymbols.drawable(name,color));image.setContentDescription(name);image.setPadding(dp(3),dp(3),dp(3),dp(3));image.setLayoutParams(new LinearLayout.LayoutParams(dp(size),dp(size)));return image;}
 private void pageTitle(String bo,String zh){selectTab(currentTab);Bilingual.apply(title,bo,zh);}
 private void showLogin(){
  destroyMap();tabs.setVisibility(View.GONE);findViewById(R.id.sync).setVisibility(View.GONE);content.removeAllViews();
  View v=getLayoutInflater().inflate(R.layout.view_login,content,false);content.addView(v);
  MaterialButton scanButton=v.findViewById(R.id.scanActivation),keyButton=v.findViewById(R.id.loginWithKey);
  EditText userInput=v.findViewById(R.id.activationUser),keyInput=v.findViewById(R.id.activationKey);TextView hint=v.findViewById(R.id.loginHint);
  setIcon(scanButton,"qr_code_2",0xFF087A64);setIcon(keyButton,"save",0xFFFFFFFF);MaterialButton logButton=v.findViewById(R.id.copyLog);setIcon(logButton,"assignment",0xFF087A64);logButton.setOnClickListener(x->copyLog());if(prefs.activated()){unlocked=true;enter();return;}unlocked=false;
  scanButton.setOnClickListener(x->scan.launch(new Intent(this,ScanActivity.class)));
  keyButton.setOnClickListener(x->{String user=userInput.getText().toString().trim().toLowerCase(Locale.ROOT),key=keyInput.getText().toString().trim();if(user.isEmpty()||!key.matches("\\d{8}")){Bilingual.apply(hint,"ཐོ་ཨང་དང་ཨང་གྲངས་8ཀྱི་གསང་ལྡེ་འཇུག་རོགས།","请输入采样员账号和8位激活密钥");return;}activateDevice(BuildConfig.DEFAULT_SERVER,user,key,scanButton,keyButton,hint);});
  if(activation!=null)activateDevice(activation.server,activation.user,activation.token,scanButton,keyButton,hint);else Bilingual.apply(hint,"ཐོ་ཨང་དང་དོ་དམ་པས་སྤྲད་པའི་གསང་ལྡེ་འཇུག་རོགས།","输入采样员账号和管理员提供的8位激活密钥；每台手机只需激活一次");
 }
 private void activateDevice(String server,String user,String key,MaterialButton scanButton,MaterialButton keyButton,TextView hint){
  Bilingual.apply(hint,"ལག་ཐོགས་ཁ་པར་སྐུལ་སློང་བྱེད་བཞིན་པ།","正在激活设备并登录…");scanButton.setEnabled(false);keyButton.setEnabled(false);
  work.execute(()->{try{JSONObject r=new Api(this).activate(server,user,key),u=r.getJSONObject("villager");prefs.save(server,r.getString("token"),u.getString("username"),u.getString("displayName"),r.getLong("deviceId"));unlocked=true;activation=null;runOnUiThread(this::enter);}catch(Exception e){db.log("error","ACTIVATE "+e.getMessage());runOnUiThread(()->{scanButton.setEnabled(true);keyButton.setEnabled(true);Bilingual.apply(hint,"སྐུལ་སློང་ཕམ་པ། ཐོ་ཨང་དང་གསང་ལྡེ་ཞིབ་བཤེར་བྱོས།","激活失败："+e.getMessage()+"\n请核对账号和一次性激活密钥");});}});
 }
 private void enter(){tabs.setVisibility(View.VISIBLE);findViewById(R.id.sync).setVisibility(View.VISIBLE);askPermissions();showMap();sync();String details="{}";try{details=new JSONObject().put("network",Util.networkType(this)).put("online",Util.online(this)).put("fineLocation",ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED).put("backgroundLocation",ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_BACKGROUND_LOCATION)==PackageManager.PERMISSION_GRANTED).put("camera",ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED).put("notifications",android.os.Build.VERSION.SDK_INT<33||ContextCompat.checkSelfPermission(this,Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED).put("pendingRecords",db.count("status!='uploaded'")).put("activeJourney",prefs.activeJourney()).toString();}catch(Exception ignored){}db.log("info","APP_READY",details);checkUpdate();}
 private void checkUpdate(){work.execute(()->{try{JSONObject v=new Api(MainActivity.this).version();String latest=v.optString("versionName","");boolean mandatory=v.optInt("mandatory",0)==1;if(!latest.isEmpty()&&!BuildConfig.VERSION_NAME.equals(latest)){String msg=(mandatory?"ངེས་པར་གསར་སྒྱུར་དགོས། / 【必须更新】未更新前请勿继续采样。\n\n":"")+"ད་ལྟའི་ཐོན་རིམ་ "+BuildConfig.VERSION_NAME+"，གསར་པ་ "+latest+"\n当前版本 "+BuildConfig.VERSION_NAME+"，最新版本 "+latest+"。请联系管理员安装新版 APP。";runOnUiThread(()->new AlertDialog.Builder(MainActivity.this).setTitle((mandatory?"ངེས་པར་གསར་སྒྱུར། / 必须更新 ":"ཐོན་རིམ་གསར་པ། / 发现新版本 ")+latest).setMessage(msg).setPositiveButton("ཤེས་སོང་། / 知道了",null).setCancelable(!mandatory).show());}}catch(Exception ignored){}});}
 private void askPermissions(){List<String> x=new ArrayList<>();if(ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)x.add(Manifest.permission.ACCESS_FINE_LOCATION);if(Build.VERSION.SDK_INT>=33&&ContextCompat.checkSelfPermission(this,Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)x.add(Manifest.permission.POST_NOTIFICATIONS);if(x.isEmpty())locations();else permissions.launch(x.toArray(new String[0]));}
 private void locations(){if(ActivityCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return;try{lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,5000,0,this);if(lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER))lm.requestLocationUpdates(LocationManager.NETWORK_PROVIDER,5000,0,this);Location x=lm.getLastKnownLocation(LocationManager.GPS_PROVIDER);if(x!=null)onLocationChanged(x);}catch(Exception e){db.log("error","LOCATION "+e.getMessage());}}
 private void sync(){if(!unlocked)return;if(syncing){Toast.makeText(this,"མཉམ་སྒྲིག་བྱེད་བཞིན་པ། / 同步中，请稍候…",Toast.LENGTH_SHORT).show();return;}syncing=true;status.setText(Util.online(this)?"ཞབས་ཞུ་ཆས་མཉམ་སྒྲིག / 正在同步服务器…":"དྲ་མེད། ཁ་པར་ནས་བེད་སྤྱོད། / 当前离线，使用手机缓存");work.execute(()->{SyncEngine.Result r;try{if(Util.online(this))try{prefs.token(new Api(this).login().getString("token"));}catch(Api.ApiError e){if(e.status==403)prefs.revoked();db.log("warning","LOGIN_REFRESH "+e.getMessage());}catch(Exception e){db.log("warning","LOGIN_REFRESH "+e.getMessage());}r=new SyncEngine(this).run();}catch(Throwable t){db.log("error","SYNC_CRASH "+t.getClass().getSimpleName()+":"+t.getMessage());r=new SyncEngine.Result();r.message="同步异常，请查看诊断日志";}final SyncEngine.Result rr=r;final int taskCount=db.tasks().size();runOnUiThread(()->{syncing=false;if(rr.deviceRevoked){unlocked=false;Toast.makeText(MainActivity.this,rr.message,Toast.LENGTH_LONG).show();showLogin();return;}status.setText("ཡར་འཇུག་བྱེད་རྒྱུ "+db.count("status!='uploaded'")+" / "+rr.message+" · 待上传");Toast.makeText(MainActivity.this,rr.message+"，任务 "+taskCount+" 个",Toast.LENGTH_SHORT).show();if(map!=null)markers();if(currentTab==1)showTasks();if(currentTab==2)showUpload();});});}
 private void showMap(){if(!unlocked)return;destroyMap();currentTab=0;pageTitle("ས་ཁྲ།","地图");content.removeAllViews();View v=getLayoutInflater().inflate(R.layout.view_map,content,false);content.addView(v);mapView=v.findViewById(R.id.map);mapView.onCreate(null);MaterialButton locateButton=v.findViewById(R.id.locate);setIcon(locateButton,"my_location",0xFFFFFFFF);locateButton.setOnClickListener(x->locate());if(mapDateFilter!=null){TextView f=new TextView(this);Bilingual.apply(f,"ཚེས་གྲངས་ "+mapDateFilter+" ཁོ་ན།","仅显示 "+mapDateFilter+" 的点位（点此显示全部日期）");f.setTextColor(0xFFFFFFFF);f.setBackgroundColor(0xCC16A27A);int pad=(int)(10*getResources().getDisplayMetrics().density);f.setPadding(pad,pad,pad,pad);f.setGravity(android.view.Gravity.CENTER);f.setOnClickListener(x->{mapDateFilter=null;showMap();});FrameLayout root=(FrameLayout)v;FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT,FrameLayout.LayoutParams.WRAP_CONTENT,android.view.Gravity.TOP);root.addView(f,lp);}mapView.getMapAsync(m->{map=m;map.setStyle(new Style.Builder().fromJson(style()),s->{markers();center();});map.setOnMarkerClickListener(marker->{Task t=markerTasks.get(marker.getId());if(t!=null)startActivity(new Intent(this,TaskActivity.class).putExtra("task",t.id));return t!=null;});map.addOnMapClickListener(p->{copyCoords(p.getLatitude(),p.getLongitude());return true;});map.addOnMapLongClickListener(p->{new AlertDialog.Builder(this).setTitle("复制该位置坐标？").setMessage(String.format(Locale.CHINA,"【WGS84】%.8f°N，%.8f°E",p.getLatitude(),p.getLongitude())).setPositiveButton("复制",(d,w)->copyCoords(p.getLatitude(),p.getLongitude())).setNegativeButton("取消",null).show();return true;});});locationText();}
 private void locate(){if(map!=null&&here!=null)map.setCameraPosition(new CameraPosition.Builder().target(new LatLng(here.getLatitude(),here.getLongitude())).zoom(14).build());if(here==null){Toast.makeText(this,"གནས་ས་ལེན་བཞིན་པ། / 正在获取WGS84位置…",Toast.LENGTH_SHORT).show();return;}new AlertDialog.Builder(this).setTitle("ངའི་གནས་ས། / 我的位置（WGS84）").setMessage(String.format(Locale.CHINA,"【WGS84】%.8f°N，%.8f°E\nཞིབ་ཚད / 精度 ±%.0fm",here.getLatitude(),here.getLongitude(),here.getAccuracy())).setPositiveButton("འདྲ་བཤུས། / 复制",(d,w)->copyCoords(here.getLatitude(),here.getLongitude())).setNegativeButton("སྒོ་རྒྱག / 关闭",null).show();}
 private void copyCoords(double lat,double lon){String s=String.format(Locale.CHINA,"【WGS84】%.8f°N，%.8f°E",lat,lon);getSystemService(android.content.ClipboardManager.class).setPrimaryClip(ClipData.newPlainText("WGS84坐标",s));Toast.makeText(this,"འདྲ་བཤུས་ཟིན། / 已复制 "+s,Toast.LENGTH_LONG).show();}
 // 采样点标记：水滴轮廓 + 历史序号文字，自动常显编号（绿=已采样 灰=已取消 蓝=进行中 橙=待采样）。
 private Icon markerIcon(Task task,int color){int w=120,h=130;Bitmap b=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);Paint fill=new Paint(Paint.ANTI_ALIAS_FLAG);fill.setColor(color);c.drawRoundRect(8,4,w-8,h-8,28,28,fill);android.graphics.drawable.Drawable sample=task.typeUi().drawable();sample.setTint(0xFFFFFFFF);sample.setBounds(34,12,86,64);sample.draw(c);Paint text=new Paint(Paint.ANTI_ALIAS_FLAG);text.setColor(0xFFFFFFFF);text.setTextSize(35);text.setFakeBoldText(true);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(MarkerLayout.fitTextSize(35f,22f,88f,text.measureText(task.siteCode())));c.drawText(task.siteCode(),w/2f,105,text);return IconFactory.getInstance(this).fromBitmap(b);}
 private String style(){String f=prefs.map();if(!f.isEmpty()&&new File(f).isFile())return"{\"version\":8,\"sources\":{\"s\":{\"type\":\"raster\",\"url\":\"mbtiles://"+f.replace("\\","/").replace(" ","%20")+"\",\"tileSize\":256}},\"layers\":[{\"id\":\"s\",\"type\":\"raster\",\"source\":\"s\"}]}";return"{\"version\":8,\"sources\":{\"s\":{\"type\":\"raster\",\"tiles\":[\"https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}\"],\"tileSize\":256,\"maxzoom\":17}},\"layers\":[{\"id\":\"s\",\"type\":\"raster\",\"source\":\"s\"}]}";}
 private void markers(){if(map==null||map.getStyle()==null)return;map.clear();markerTasks.clear();Map<String,List<Task>> groups=new LinkedHashMap<>();for(Task t:db.tasks()){if(t.canceled())continue;if(mapDateFilter!=null&&!mapDateFilter.equals(t.j.optString("planned_date","未定日期")))continue;long siteId=t.j.optLong("site_id");String key=siteId>0?"site:"+siteId:String.format(Locale.ROOT,"coord:%.7f:%.7f",t.lat(),t.lon());groups.computeIfAbsent(key,k->new ArrayList<>()).add(t);}for(List<Task> group:groups.values()){for(int index=0;index<group.size();index++){Task t=group.get(index);MarkerLayout.Position position=MarkerLayout.spread(t.lat(),t.lon(),index,group.size());int color=t.submitted()?0xFF16A27A:0xFFEF9C2F;String prefix=t.submitted()?"ཟིན / 已采样 ":"ལེན་རྒྱུ / 待采样 ";String count=group.size()>1?" ×"+group.size():"";Marker m=map.addMarker(new MarkerOptions().position(new LatLng(position.latitude,position.longitude)).icon(markerIcon(t,color)).title(prefix+t.title()+count).snippet(t.typeUi().inline()+" · "+t.code()));markerTasks.put(m.getId(),t);}}if(here!=null)map.addMarker(new MarkerOptions().position(new LatLng(here.getLatitude(),here.getLongitude())).title("ངའི་གནས་ས། / 我的位置（WGS84）"));}
 protected void onNewIntent(Intent i){super.onNewIntent(i);if(prefs.activated()&&unlocked)showMap();}
 private void center(){if(map!=null&&here!=null)map.setCameraPosition(new CameraPosition.Builder().target(new LatLng(here.getLatitude(),here.getLongitude())).zoom(14).build());}
 private int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+0.5f);}
 private GradientDrawable shape(int color,float radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
 private TextView smallBadge(String value,int color){TextView v=new TextView(this);v.setText(value);v.setTextSize(11);v.setTextColor(color);v.setTypeface(null,android.graphics.Typeface.BOLD);v.setPadding(dp(6),dp(3),dp(6),dp(3));v.setBackground(shape(0xFFE4F3EF,14));return v;}
 private void showTasks(){
  if(!unlocked)return;destroyMap();currentTab=1;pageTitle("ངའི་ལས་འགན།","我的任务");content.removeAllViews();
  View root=getLayoutInflater().inflate(R.layout.view_list,content,false);content.addView(root);
  LinearLayout datesView=root.findViewById(R.id.dateTaskList),pointsView=root.findViewById(R.id.pointList);
  TextView pointTitle=root.findViewById(R.id.pointPanelTitle),pointSummary=root.findViewById(R.id.pointPanelSummary);
  List<Task> visible=new ArrayList<>();for(Task t:db.tasks())if(!t.canceled())visible.add(t);
  java.util.Map<String,List<Task>> groups=new java.util.TreeMap<>(Comparator.reverseOrder());for(Task t:visible)groups.computeIfAbsent(t.plannedDate(),k->new ArrayList<>()).add(t);
  List<String> dates=new ArrayList<>(groups.keySet());
  if(dates.isEmpty()){datesView.addView(emptyText("ལས་འགན་མེད།\n暂无下发任务\n\nདྲ་ལ་མཐུད་ནས་མཉམ་སྒྲིག་མནན།\n请联网后点击右上角同步"));Bilingual.apply(pointTitle,"ཚེས་གྲངས་ལས་འགན་མེད།","暂无日期任务");pointSummary.setText("");return;}
  for(List<Task> list:groups.values())list.sort(Comparator.comparing(Task::code));final String first=dates.get(0);
  for(String date:dates){List<Task> list=groups.get(date);int done=0;for(Task t:list)if(t.submitted())done++;
   LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(9),dp(9),dp(7),dp(9));card.setBackground(shape(date.equals(first)?0xFFDDF3ED:0xFFFFFFFF,12));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,LinearLayout.LayoutParams.WRAP_CONTENT);cp.setMargins(0,0,0,dp(8));card.setLayoutParams(cp);
   TextView d=new TextView(this);d.setText(date);d.setTextSize(15);d.setTypeface(null,android.graphics.Typeface.BOLD);d.setTextColor(0xFF09262B);card.addView(d);
   LinearLayout stats=new LinearLayout(this);stats.setOrientation(LinearLayout.VERTICAL);TextView ok=smallBadge("ཟིན "+done+" / 已采 "+done,0xFF087A64);TextView pending=smallBadge("མ་ཟིན "+(list.size()-done)+" / 未采 "+(list.size()-done),0xFFD06A00);stats.addView(ok);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-2,-2);pp.setMargins(0,dp(3),0,0);stats.addView(pending,pp);card.addView(stats);
   card.setOnClickListener(v->{mapDateFilter=date;renderPointsForDate(date,groups,pointsView,pointTitle,pointSummary);for(int i=0;i<datesView.getChildCount();i++){View x=datesView.getChildAt(i);if(x instanceof LinearLayout)x.setBackground(shape(x==card?0xFFDDF3ED:0xFFFFFFFF,12));}});datesView.addView(card);
  }
  renderPointsForDate(first,groups,pointsView,pointTitle,pointSummary);
 }
 private TextView emptyText(String s){TextView v=new TextView(this);v.setText(s);v.setTextSize(15);v.setTextColor(0xFF55706D);v.setGravity(Gravity.CENTER);v.setPadding(dp(12),dp(40),dp(12),dp(40));return v;}
 private void renderPointsForDate(String date,java.util.Map<String,List<Task>> groups,LinearLayout out,TextView titleView,TextView summary){
  out.removeAllViews();List<Task> list=groups.get(date);if(list==null||list.isEmpty()){titleView.setText(date);summary.setText("དཔེ་ཚད་ས་གནས་མེད། / 暂无采样点");return;}
  int done=0;for(Task t:list)if(t.submitted())done++;titleView.setText(date);summary.setText("ས་གནས "+list.size()+" · ཟིན "+done+" · མ་ཟིན "+(list.size()-done)+"\n采样点 "+list.size()+" · 已完成 "+done+" · 待采样 "+(list.size()-done));
  for(Task t:list){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.HORIZONTAL);card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(8),dp(8),dp(6),dp(8));card.setBackground(shape(0xFFFFFFFF,12));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,LinearLayout.LayoutParams.WRAP_CONTENT);cp.setMargins(0,0,0,dp(8));card.setLayoutParams(cp);
   ImageView sample=symbol(t.typeUi().icon,t.typeUi().color,42);sample.setContentDescription(t.typeUi().inline());card.addView(sample);
   LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);info.setPadding(dp(7),0,dp(2),0);
   TextView name=new TextView(this);Bilingual.apply(name,t.titleBo(),t.title());name.setTextSize(16);name.setTypeface(null,android.graphics.Typeface.BOLD);name.setTextColor(0xFF09262B);info.addView(name);
   TextView meta=new TextView(this);String time=t.plannedTime().isEmpty()?"计划时间未设置":"计划 "+t.plannedTime();meta.setText(t.typeUi().inline()+" · "+t.code()+" · "+time);meta.setTextSize(11);meta.setTextColor(0xFF55706D);info.addView(meta);
   TextView owner=new TextView(this);owner.setText(t.statusBo()+" / "+t.statusLabel()+" · "+t.villagerName()+" · "+t.deviceName());owner.setTextSize(11);owner.setTextColor(t.submitted()?0xFF087A64:0xFFD06A00);info.addView(owner);card.addView(info,new LinearLayout.LayoutParams(0,-2,1));
   ImageView arrow=symbol("chevron_right",0xFF6B7C7A,32);arrow.setContentDescription("ཞིབ་ཕྲ། / 进入详情");card.addView(arrow,new LinearLayout.LayoutParams(dp(32),dp(48)));
   TextView timeEditor=meta;timeEditor.setOnClickListener(v->editPlannedTime(t,timeEditor));card.setOnClickListener(v->startActivity(new Intent(this,TaskActivity.class).putExtra("task",t.id)));out.addView(card);
  }
 }
 private void editPlannedTime(Task t,TextView label){if(t.submitted()){Toast.makeText(this,"ལས་འགན་འདི་ཟིན། / 已采样任务不能修改计划时间",Toast.LENGTH_SHORT).show();return;}int hour=9,minute=0;try{if(!t.plannedTime().isEmpty()){String[] p=t.plannedTime().split(":");hour=Integer.parseInt(p[0]);minute=Integer.parseInt(p[1]);}}catch(Exception ignored){}new TimePickerDialog(this,(v,h,m)->{String value=String.format(Locale.CHINA,"%02d:%02d",h,m);db.setPlannedTime(t.id,value);label.setText(t.typeUi().inline()+" · 计划 "+value);androidx.work.WorkManager.getInstance(this).enqueue(new androidx.work.OneTimeWorkRequest.Builder(SyncWorker.class).setConstraints(new androidx.work.Constraints.Builder().setRequiredNetworkType(androidx.work.NetworkType.CONNECTED).build()).build());work.execute(()->{try{if(!Util.online(this))throw new IOException("离线");new Api(this).schedule(t.id,value);db.scheduleDone(t.id);runOnUiThread(()->Toast.makeText(this,"དུས་ཚོད་ཉར་ཟིན། / 计划时间已保存",Toast.LENGTH_SHORT).show());}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"ཁ་པར་ནང་ཉར་ཟིན། / 已保存到手机，联网后自动同步",Toast.LENGTH_SHORT).show());}});},hour,minute,true).show();}
 private void showUpload(){if(!unlocked)return;destroyMap();currentTab=2;pageTitle("ཡར་འཇུག","上传");LinearLayout p=panel();int pending=db.count("status!='uploaded'"),done=db.count("status='uploaded'");bilingualText(p,"ཡར་འཇུག་མ་ཟིན་ "+pending+"　·　ཟིན་ "+done,"未上传 "+pending+" 条　·　已上传 "+done+" 条",21);bilingualText(p,"དྲ་ཡོད་དུས་རང་འགུལ་གྱིས་ཡར་འཇུག་བྱེད།","有网络时自动同步；未上传数据一直保存在手机，不会丢失。",14);for(JSONObject r:db.recordsAll()){Task t=db.task(r.optLong("taskId"));String code=t==null?("任务 "+r.optLong("taskId")):t.code();String state=r.optString("status");if(state.equals("uploaded")){String at=r.optString("uploadedAt").replace('T',' ');if(at.length()>16)at=at.substring(0,16);statusRow(p,"cloud_done",0xFF087A64,"ཡར་འཇུག་ཟིན།　"+code,"已上传　"+code+"　"+at);}else{String err=r.optString("error");if(err.length()>70)err=err.substring(0,70)+"…";boolean failed=state.equals("failed");statusRow(p,failed?"warning":"hourglass_top",failed?0xFFB3261E:0xFFD06A00,failed?"ཡར་འཇུག་ཕམ་པ།　"+code:"ཡར་འཇུག་བྱེད་རྒྱུ།　"+code,failed?"上传失败，将自动重试　"+code+"　"+friendlyUploadError(err):"等待上传　"+code);}}MaterialButton b=button("ཡང་བསྐྱར་མཉམ་སྒྲིག","立即重试同步","sync");b.setOnClickListener(v->{sync();showUpload();});p.addView(b);content.removeAllViews();content.addView(p);}
 private String friendlyUploadError(String error){String e=error==null?"":error.toLowerCase(Locale.ROOT);if(e.contains("401")||e.contains("403")||e.contains("失效"))return"本手机已失效，请联系管理员";if(e.contains("photo")||e.contains("照片")||e.contains("file"))return"照片文件异常，请联系管理员";if(e.contains("timeout")||e.contains("network")||e.contains("网络")||e.contains("failed to connect"))return"暂无网络，将自动重试";return error==null||error.isBlank()?"服务器暂时不可用，将自动重试":error;}
 private void showMine(){if(!unlocked)return;destroyMap();currentTab=3;pageTitle("ངའི།","我的");LinearLayout p=panel();bilingualText(p,"སྤྱོད་མཁན། "+prefs.name(),prefs.name()+"（"+prefs.user()+"）",21);bilingualText(p,"ཞབས་ཞུ་ཆས་དང་ལག་ཐོགས་ཆ་འཕྲིན།","服务器："+prefs.server()+"\n设备："+Util.uuid(this)+"\n坐标：WGS84\n版本："+BuildConfig.VERSION_NAME,15);MaterialButton map=button("དྲ་མེད་ས་ཁྲ།",prefs.map().isEmpty()?"导入离线卫星地图包（MBTiles）":"更换离线地图包","map");map.setOnClickListener(v->mapFile.launch("*/*"));p.addView(map);MaterialButton log=button("ནད་བརྟག་ཟིན་ཐོ།","复制诊断日志","assignment");log.setOnClickListener(v->copyLog());p.addView(log);MaterialButton csv=button("ཟིན་ཐོ་བགོ་བཤའ།","分享日志文件（Excel可打开）","cloud_upload");csv.setOnClickListener(v->{java.io.File f=db.logsCsv();if(f==null){Toast.makeText(this,"生成日志文件失败",Toast.LENGTH_LONG).show();return;}try{android.net.Uri u=androidx.core.content.FileProvider.getUriForFile(this,"online.gpsgps.bscsampling.files",f);Intent s=new Intent(Intent.ACTION_SEND).setType("text/csv").putExtra(Intent.EXTRA_STREAM,u).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(s,"分享日志文件"));}catch(Exception e){Toast.makeText(this,"分享失败："+e.getMessage(),Toast.LENGTH_LONG).show();}});p.addView(csv);content.removeAllViews();content.addView(p);}
 private LinearLayout panel(){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(16),dp(16),dp(16),dp(16));return p;}
 private void text(LinearLayout p,String s,int size){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(Color.DKGRAY);v.setPadding(dp(10),dp(12),dp(10),dp(12));p.addView(v);}
 private void bilingualText(LinearLayout p,String bo,String zh,int size){TextView v=new TextView(this);Bilingual.apply(v,bo,zh);v.setTextSize(size);v.setTextColor(0xFF09262B);v.setPadding(dp(10),dp(12),dp(10),dp(12));p.addView(v);}
 private void statusRow(LinearLayout p,String iconName,int color,String bo,String zh){TextView v=new TextView(this);Bilingual.apply(v,bo,zh);v.setTextSize(16);v.setTextColor(color);v.setPadding(dp(12),dp(12),dp(12),dp(12));android.graphics.drawable.Drawable d=MaterialSymbols.drawable(iconName,color);d.setBounds(0,0,dp(30),dp(30));v.setCompoundDrawablePadding(dp(10));v.setCompoundDrawables(d,null,null,null);v.setBackground(shape(0xFFFFFFFF,12));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(8));p.addView(v,lp);}
 private MaterialButton button(String bo,String zh,String iconName){MaterialButton b=new MaterialButton(this);Bilingual.applyOnColor(b,bo,zh);b.setTextSize(16);b.setMinHeight(dp(68));setIcon(b,iconName,0xFFFFFFFF);return b;}
 private void importMap(Uri u){if(u==null)return;work.execute(()->{try{long declared=-1;try(Cursor c=getContentResolver().query(u,new String[]{OpenableColumns.SIZE},null,null,null)){if(c!=null&&c.moveToFirst())declared=c.getLong(0);}if(declared>2_000_000_000L)throw new IOException("地图包超过2GB");File out=new File(getFilesDir(),"basongcuo.mbtiles");try(InputStream in=getContentResolver().openInputStream(u);FileOutputStream o=new FileOutputStream(out)){byte[] b=new byte[1024*1024];int n;long total=0;while((n=in.read(b))>=0){total+=n;if(total>2_000_000_000L)throw new IOException("地图包超过2GB");o.write(b,0,n);}}byte[] h=new byte[16];try(FileInputStream in=new FileInputStream(out)){if(in.read(h)!=16||!new String(h,StandardCharsets.US_ASCII).startsWith("SQLite format 3"))throw new IOException("不是有效MBTiles地图包");}prefs.map(out.getPath());runOnUiThread(()->Toast.makeText(this,"离线地图导入成功",Toast.LENGTH_LONG).show());}catch(Exception e){db.log("error","MAP_IMPORT "+e.getMessage());runOnUiThread(()->Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show());}});}
 private void copyLog(){getSystemService(android.content.ClipboardManager.class).setPrimaryClip(ClipData.newPlainText("巴松措采样日志",db.diagnostics()));Toast.makeText(this,"ཟིན་ཐོ་འདྲ་བཤུས་ཟིན། / 日志已复制，可以发给管理员",Toast.LENGTH_LONG).show();}
 public void onLocationChanged(@NonNull Location l){here=l;locationText();if(map!=null)markers();}private void locationText(){TextView v=content.findViewById(R.id.location);if(v!=null)v.setText(here==null?"གནས་ས་ལེན་བཞིན་པ། / 正在获取WGS84位置…":String.format(Locale.CHINA,"གནས་ས། / 位置　WGS84 %.6f, %.6f\nཞིབ་ཚད། / 精度　±%.0fm",here.getLatitude(),here.getLongitude(),here.getAccuracy()));}
 private void destroyMap(){if(mapView!=null){mapView.onStop();mapView.onDestroy();mapView=null;map=null;}}
 protected void onStart(){super.onStart();if(mapView!=null)mapView.onStart();}protected void onResume(){super.onResume();if(mapView!=null)mapView.onResume();}protected void onPause(){if(mapView!=null)mapView.onPause();super.onPause();}protected void onStop(){if(mapView!=null)mapView.onStop();super.onStop();}public void onLowMemory(){super.onLowMemory();if(mapView!=null)mapView.onLowMemory();}protected void onDestroy(){try{lm.removeUpdates(this);}catch(Exception ignored){}try{if(netCallback!=null)getSystemService(ConnectivityManager.class).unregisterNetworkCallback(netCallback);}catch(Exception ignored){}destroyMap();work.shutdown();super.onDestroy();}
}
