package online.gpsgps.bscsampling;

import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.os.Bundle;import android.widget.Toast;import androidx.activity.result.*;import androidx.activity.result.contract.ActivityResultContracts;import androidx.appcompat.app.AppCompatActivity;import androidx.camera.core.*;import androidx.camera.lifecycle.ProcessCameraProvider;import androidx.camera.view.PreviewView;import androidx.core.content.ContextCompat;import com.google.android.material.button.MaterialButton;import com.google.common.util.concurrent.ListenableFuture;import org.json.JSONArray;import java.io.File;import java.io.IOException;import java.util.Locale;import java.util.concurrent.*;

public final class PhotoActivity extends AppCompatActivity{static final String PATH="path",AT="at",WEATHER="weather";private PreviewView camera;private MaterialButton shutter;private ImageCapture capture;private final ExecutorService work=Executors.newSingleThreadExecutor();private final ActivityResultLauncher<String> permission=registerForActivityResult(new ActivityResultContracts.RequestPermission(),ok->{if(ok)camera();else finish();});
 protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_photo);camera=findViewById(R.id.camera);shutter=findViewById(R.id.shutter);shutter.setOnClickListener(v->shoot());if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)camera();else permission.launch(Manifest.permission.CAMERA);}
 private void camera(){ListenableFuture<ProcessCameraProvider> f=ProcessCameraProvider.getInstance(this);f.addListener(()->{try{ProcessCameraProvider p=f.get();Preview v=new Preview.Builder().build();v.setSurfaceProvider(camera.getSurfaceProvider());capture=new ImageCapture.Builder().setCaptureMode(ImageCapture.CAPTURE_MODE_MAXIMIZE_QUALITY).setJpegQuality(95).build();p.unbindAll();p.bindToLifecycle(this,CameraSelector.DEFAULT_BACK_CAMERA,v,capture);}catch(Exception e){Toast.makeText(this,"相机启动失败",Toast.LENGTH_LONG).show();}},ContextCompat.getMainExecutor(this));}
 private void shoot(){if(capture==null)return;shutter.setEnabled(false);shutter.setText("正在加水印…");File raw=new File(getCacheDir(),"raw-"+System.currentTimeMillis()+".jpg");capture.takePicture(new ImageCapture.OutputFileOptions.Builder(raw).build(),work,new ImageCapture.OnImageSavedCallback(){public void onImageSaved(ImageCapture.OutputFileResults r){try{String at=Util.now();double lat=getIntent().getDoubleExtra("lat",0),lon=getIntent().getDoubleExtra("lon",0);String weather="待补充";if(Util.online(PhotoActivity.this))try{weather=new Api(PhotoActivity.this).weather(lat,lon,at);}catch(Exception ignored){}File dir=new File(getFilesDir(),"watermarked");if(!dir.exists()&&!dir.mkdirs())throw new IOException("无法建立照片目录");File out=new File(dir,"sample-"+System.currentTimeMillis()+".jpg");JSONArray lines=new JSONArray().put(getIntent().getStringExtra("project")+"　"+getIntent().getStringExtra("code")+"　"+getIntent().getStringExtra("type")).put(getIntent().getStringExtra("site")+"（历史 "+getIntent().getStringExtra("siteCode")+"）　采样员："+new Prefs(PhotoActivity.this).name()).put(String.format(Locale.CHINA,"WGS84 %.6f, %.6f　距点 %.0fm　精度 ±%.0fm",lat,lon,getIntent().getDoubleExtra("distance",0),getIntent().getDoubleExtra("accuracy",0))).put(at.replace('T',' ')+"　天气："+weather);Watermark.render(raw,out,lines);raw.delete();String w=weather;runOnUiThread(()->{setResult(RESULT_OK,new Intent().putExtra(PATH,out.getPath()).putExtra(AT,at).putExtra(WEATHER,w));finish();});}catch(Exception e){new Store(PhotoActivity.this).log("error","PHOTO "+e.getMessage());runOnUiThread(()->{shutter.setEnabled(true);shutter.setText("重新拍照");Toast.makeText(PhotoActivity.this,e.getMessage(),Toast.LENGTH_LONG).show();});}}public void onError(ImageCaptureException e){runOnUiThread(()->{shutter.setEnabled(true);shutter.setText("重新拍照");});}});}
 protected void onDestroy(){work.shutdown();super.onDestroy();}}
