package online.gpsgps.bscsampling;
import android.Manifest;import android.app.Application;import android.app.NotificationChannel;import android.app.NotificationManager;import android.content.pm.PackageManager;import androidx.core.content.ContextCompat;import androidx.work.*;import org.json.JSONObject;import java.util.concurrent.TimeUnit;
public final class SamplingApp extends Application{static final String TRACK="tracking";public void onCreate(){super.onCreate();
  // 全局崩溃捕获：把崩溃堆栈写入本地日志表（随诊断日志上传），便于远程定位闪退；
  // 只记录异常摘要与堆栈，不含任何敏感数据。
  final Thread.UncaughtExceptionHandler prev=Thread.getDefaultUncaughtExceptionHandler();
  Thread.setDefaultUncaughtExceptionHandler((t,e)->{try{StringBuilder s=new StringBuilder("CRASH ").append(t.getName()).append(' ').append(e.getClass().getSimpleName());if(e.getMessage()!=null)s.append(": ").append(e.getMessage());StackTraceElement[] st=e.getStackTrace();for(int i=0;i<Math.min(st.length,12);i++)s.append("\n  at ").append(st[i].toString());new Store(this).log("error",s.toString());}catch(Exception ignored){}if(prev!=null)prev.uncaughtException(t,e);else{android.os.Process.killProcess(android.os.Process.myPid());System.exit(10);}});
  getSystemService(NotificationManager.class).createNotificationChannel(new NotificationChannel(TRACK,"采样轨迹记录",NotificationManager.IMPORTANCE_LOW));String details="{}";try{details=new JSONObject().put("fineLocation",granted(Manifest.permission.ACCESS_FINE_LOCATION)).put("backgroundLocation",granted(Manifest.permission.ACCESS_BACKGROUND_LOCATION)).put("camera",granted(Manifest.permission.CAMERA)).put("network",Util.networkType(this)).put("sdk",android.os.Build.VERSION.SDK_INT).toString();}catch(Exception ignored){}new Store(this).log("info","APP_START "+BuildConfig.VERSION_NAME+" "+android.os.Build.MANUFACTURER+"/"+android.os.Build.MODEL+" Android "+android.os.Build.VERSION.RELEASE,details);Constraints c=new Constraints.Builder().setRequiredNetworkType(NetworkType.CONNECTED).build();WorkManager.getInstance(this).enqueueUniquePeriodicWork("sync",ExistingPeriodicWorkPolicy.UPDATE,new PeriodicWorkRequest.Builder(SyncWorker.class,15,TimeUnit.MINUTES).setConstraints(c).build());}
private boolean granted(String p){return ContextCompat.checkSelfPermission(this,p)==PackageManager.PERMISSION_GRANTED;}}
