package online.gpsgps.bscsampling;

import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.os.*;import android.view.View;import android.widget.TextView;import androidx.activity.result.*;import androidx.activity.result.contract.ActivityResultContracts;import androidx.appcompat.app.AppCompatActivity;import androidx.camera.core.*;import androidx.camera.lifecycle.ProcessCameraProvider;import androidx.camera.view.PreviewView;import androidx.core.content.ContextCompat;import com.google.android.material.button.MaterialButton;import com.google.common.util.concurrent.ListenableFuture;import com.google.zxing.*;import com.google.zxing.common.HybridBinarizer;import java.nio.ByteBuffer;import java.util.*;import java.util.concurrent.*;

public final class ScanActivity extends AppCompatActivity{
  static final String RESULT="scan",DAMAGED="damaged";private PreviewView camera;private TextView timer;private MaterialButton damaged;private final ExecutorService worker=Executors.newSingleThreadExecutor();private final Handler h=new Handler(Looper.getMainLooper());private long start,lastFail;private int fails;private volatile boolean done;
  private final ActivityResultLauncher<String> permission=registerForActivityResult(new ActivityResultContracts.RequestPermission(),ok->{if(ok)camera();else finish();});
  protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_scan);camera=findViewById(R.id.camera);timer=findViewById(R.id.timer);damaged=findViewById(R.id.damaged);damaged.setOnClickListener(v->{setResult(RESULT_OK,new Intent().putExtra(DAMAGED,true));finish();});start=System.currentTimeMillis();h.post(tick);if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)camera();else permission.launch(Manifest.permission.CAMERA);}
  private final Runnable tick=new Runnable(){public void run(){long sec=(System.currentTimeMillis()-start)/1000;timer.setText("已扫描 "+sec+" 秒 · 失败 "+fails+" 次");if(sec>=10||fails>=3)damaged.setVisibility(View.VISIBLE);if(!done)h.postDelayed(this,1000);}};
  private void camera(){ListenableFuture<ProcessCameraProvider> f=ProcessCameraProvider.getInstance(this);f.addListener(()->{try{ProcessCameraProvider p=f.get();Preview v=new Preview.Builder().build();v.setSurfaceProvider(camera.getSurfaceProvider());ImageAnalysis a=new ImageAnalysis.Builder().setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST).build();a.setAnalyzer(worker,image->{try{if(done)return;ImageProxy.PlaneProxy plane=image.getPlanes()[0];ByteBuffer b=plane.getBuffer();byte[] raw=new byte[b.remaining()];b.get(raw);int w=image.getWidth(),ht=image.getHeight(),stride=plane.getRowStride();byte[] y=raw;if(stride!=w){y=new byte[w*ht];for(int row=0;row<ht;row++)System.arraycopy(raw,row*stride,y,row*w,w);}PlanarYUVLuminanceSource source=new PlanarYUVLuminanceSource(y,w,ht,0,0,w,ht,false);com.google.zxing.Result r=decode(source);if(r==null&&source.isRotateSupported())r=decode(source.rotateCounterClockwise());if(r!=null)deliver(r.getText());else failure();}catch(Exception e){failure();}finally{image.close();}});p.unbindAll();p.bindToLifecycle(this,CameraSelector.DEFAULT_BACK_CAMERA,v,a);}catch(Exception e){timer.setText("相机启动失败："+e.getMessage());new Store(this).log("error","SCAN_CAMERA "+e.getMessage());}},ContextCompat.getMainExecutor(this));}
  private com.google.zxing.Result decode(LuminanceSource s){try{Map<DecodeHintType,Object> hints=new EnumMap<>(DecodeHintType.class);hints.put(DecodeHintType.TRY_HARDER,true);hints.put(DecodeHintType.CHARACTER_SET,"UTF-8");return new MultiFormatReader().decode(new BinaryBitmap(new HybridBinarizer(s)),hints);}catch(NotFoundException e){return null;}}
  private void failure(){long n=System.currentTimeMillis();if(n-lastFail>=3000){fails++;lastFail=n;}}private void deliver(String s){if(done)return;done=true;runOnUiThread(()->{setResult(RESULT_OK,new Intent().putExtra(RESULT,s));finish();});}protected void onDestroy(){done=true;h.removeCallbacksAndMessages(null);worker.shutdown();super.onDestroy();}
}
