package online.gpsgps.bscsampling;
import android.graphics.Bitmap;

import android.Manifest;import android.app.AlertDialog;import android.content.*;import android.content.pm.PackageManager;import android.graphics.BitmapFactory;import android.location.*;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.view.View;import android.widget.*;import androidx.activity.result.*;import androidx.activity.result.contract.ActivityResultContracts;import androidx.annotation.NonNull;import androidx.appcompat.app.AppCompatActivity;import androidx.core.app.ActivityCompat;import androidx.core.content.ContextCompat;import androidx.work.*;import com.google.android.material.button.MaterialButton;import org.json.JSONObject;import java.io.File;import java.util.Locale;import java.util.concurrent.*;import okhttp3.*;

public final class TaskActivity extends AppCompatActivity implements LocationListener{
 private static final String[] REASONS={"无水","河岸无法靠近","道路中断","水位或地质危险","二维码损坏","其他"};private static final String[] REASON_LABELS={"ཆུ་མེད། / 无水","ཆུ་ཁར་འགྲོ་མི་ཐུབ། / 河岸无法靠近","ལམ་ཆད། / 道路中断","ཉེན་ཁ། / 水位或地质危险","ཨང་རྟགས་ཆག / 二维码损坏","གཞན། / 其他"};private Store db;private Prefs prefs;private Task task;private LocationManager lm;private Location here;private String journey,qr="",reason="",detail="",photo="",captured="",weather="待补充";private boolean manual,noWater;private TextView loc,message;private MaterialButton start,scan,photoButton,save;private ImageView preview;private final ExecutorService work=Executors.newSingleThreadExecutor();private final Handler ui=new Handler(Looper.getMainLooper());private final Runnable autoTick=()->{};
 private final ActivityResultLauncher<String[]> foreground=registerForActivityResult(new ActivityResultContracts.RequestMultiplePermissions(),r->permissionGuide());private final ActivityResultLauncher<Intent> scanner=registerForActivityResult(new ActivityResultContracts.StartActivityForResult(),r->scanResult(r.getResultCode(),r.getData()));private final ActivityResultLauncher<Intent> camera=registerForActivityResult(new ActivityResultContracts.StartActivityForResult(),r->photoResult(r.getResultCode(),r.getData()));
 protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_task);db=new Store(this);prefs=new Prefs(this);task=db.task(getIntent().getLongExtra("task",-1));if(task==null){Toast.makeText(this,"ལས་འགན་མེད། / 任务不存在，请同步",Toast.LENGTH_LONG).show();finish();return;}lm=getSystemService(LocationManager.class);bind();fill();reference();submittedPhoto();if(task.submitted())loc.setText("དཔེ་ཚད་བླངས་ཟིན། / 已采样记录");if(!task.submitted())locations();journey=db.active(task.j.optLong("site_id"));if(journey!=null&&!task.submitted()){Bilingual.apply(start,"འགྲོ་ལམ་ཟིན་ཐོ་འགོ་བཙུགས།","正在记录前往轨迹");start.setEnabled(false);scan.setEnabled(true);}}
 private void setIcon(MaterialButton button,String name,int color){button.setIcon(MaterialSymbols.drawable(name,color));button.setIconTint(null);button.setIconSize((int)(24*getResources().getDisplayMetrics().density));button.setIconPadding((int)(8*getResources().getDisplayMetrics().density));}
 private void bind(){MaterialButton back=findViewById(R.id.back);back.setOnClickListener(v->finish());setIcon(back,"arrow_back",0xFF087A64);loc=findViewById(R.id.locationState);message=findViewById(R.id.message);start=findViewById(R.id.start);scan=findViewById(R.id.scanBottle);photoButton=findViewById(R.id.takePhoto);save=findViewById(R.id.save);preview=findViewById(R.id.photoPreview);ImageView typeIcon=findViewById(R.id.sampleTypeIcon);typeIcon.setImageDrawable(task.typeUi().drawable());typeIcon.setContentDescription(task.typeUi().inline());setIcon(start,"route",0xFFFFFFFF);setIcon(scan,"qr_code_2",0xFFFFFFFF);setIcon(photoButton,"photo_camera",0xFFFFFFFF);setIcon(save,"save",0xFFFFFFFF);MaterialButton noWater=findViewById(R.id.noWater);setIcon(noWater,"warning",0xFFB3261E);start.setOnClickListener(v->start());scan.setOnClickListener(v->scan());noWater.setOnClickListener(v->noWater());photoButton.setOnClickListener(v->photo());save.setOnClickListener(v->save());}
 private void fill(){Bilingual.apply((TextView)findViewById(R.id.taskTitle),task.titleBo(),task.title());((TextView)findViewById(R.id.code)).setText(task.code());String planned=task.j.optString("planned_date");String time=task.j.optString("planned_time","");((TextView)findViewById(R.id.meta)).setText(task.typeUi().inline()+" · 历史序号 "+task.siteCode()+" · 计划 "+planned+(time.isEmpty()?"":" "+time));String remarks=task.j.optString("remarks","").trim(),instructions=task.j.optString("instructions","").trim();String zh=(instructions.isEmpty()?"":instructions+"\n")+(remarks.isEmpty()?"暂无备注":remarks);Bilingual.apply((TextView)findViewById(R.id.instructions),task.instructionsBo(),"采样说明 / 备注\n"+zh);TextView risk=findViewById(R.id.risk);String riskZh=task.j.optString("risk_note","").trim();if(task.riskBo().isBlank()&&riskZh.isBlank())risk.setVisibility(View.GONE);else{Bilingual.apply(risk,task.riskBo(),"风险提醒\n"+riskZh);risk.setVisibility(View.VISIBLE);}if(task.submitted()){findViewById(R.id.steps).setVisibility(View.GONE);start.setVisibility(View.GONE);scan.setVisibility(View.GONE);findViewById(R.id.noWater).setVisibility(View.GONE);photoButton.setVisibility(View.GONE);save.setVisibility(View.GONE);}}
 private void locations(){if(ActivityCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){foreground.launch(Build.VERSION.SDK_INT>=33?new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.POST_NOTIFICATIONS}:new String[]{Manifest.permission.ACCESS_FINE_LOCATION});return;}try{lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,2000,0,this);if(lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER))lm.requestLocationUpdates(LocationManager.NETWORK_PROVIDER,3000,0,this);}catch(Exception e){message.setText("གནས་ས་འགོ་སློང་མ་ཐུབ། / 定位启动失败："+e.getMessage());}}
 private boolean permissions(){return ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED&&(Build.VERSION.SDK_INT<29||ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_BACKGROUND_LOCATION)==PackageManager.PERMISSION_GRANTED)&&(Build.VERSION.SDK_INT<33||ContextCompat.checkSelfPermission(this,Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED);}
 private void permissionGuide(){if(permissions()){locations();message.setText("ཆོག་མཆན་ཁ་ཕྱེ་ཟིན། / 权限已开启");return;}new AlertDialog.Builder(this).setTitle("གནས་ས་དང་བརྡ་ཐོ་ཁ་ཕྱེ་དགོས། / 必须开启定位与通知").setMessage("1　ཞིབ་ཚད་གནས་ས། / 精确位置：允许\n2　གནས་ས་རྟག་ཏུ། / 位置信息：始终允许\n3　བརྡ་ཐོ། / 通知：允许\n\nཐེངས་འདི་ཁོ་ན་མ་འདེམས། / 请不要选择“仅本次”。").setPositiveButton("ཁ་ཕྱེ་བ། / 去开启",(d,w)->startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())))).setNegativeButton("ད་ལྟ་མི་ལེན། / 暂不采样",null).show();}
 private void start(){if(!permissions()){db.log("warning","PERM_DENIED_START",permDetail());permissionGuide();return;}if(here==null){message.setText("ཕྱི་རོལ་དུ་གནས་ས་སྒུག་རོགས། / 请到室外等待卫星定位");return;}db.log("info","START_JOURNEY",permDetail());String shared=db.active(task.j.optLong("site_id"));if(shared!=null){activate(shared,false,true);return;}start.setEnabled(false);Bilingual.apply(start,"འགྲོ་ལམ་ཟིན་ཐོ་བཟོ་བཞིན་པ།","正在建立轨迹…");Location pos=new Location(here);if(!Util.online(this)){activate(db.journey(task.id,task.j.optLong("site_id"),pos,true),true,true);return;}work.execute(()->{String local=db.journey(task.id,task.j.optLong("site_id"),pos,false);try{JSONObject r=new Api(this).start(task.id,pos.getLatitude(),pos.getLongitude(),pos.getAccuracy());db.serverJourney(local,r.getJSONObject("journey").getLong("id"));runOnUiThread(()->activate(local,r.optBoolean("weakEvidence"),true));}catch(Api.ApiError e){db.abort(local);runOnUiThread(()->{start.setEnabled(true);Bilingual.apply(start,"1 ས་གནས་སུ་འགྲོ།（འདེམས་རུང་）","开始前往（可选，记录轨迹）");message.setText(e.getMessage());});}catch(Exception e){db.offlineJourney(local);db.log("warning","OFFLINE_START "+e.getMessage());runOnUiThread(()->activate(local,true,true));}});}
 private String permDetail(){try{return new org.json.JSONObject().put("network",Util.networkType(this)).put("online",Util.online(this)).put("distance",Math.round(distance())).put("fineLocation",ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED).put("backgroundLocation",ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_BACKGROUND_LOCATION)==PackageManager.PERMISSION_GRANTED).toString();}catch(Exception e){return"{}";}}
 private void activate(String id,boolean weak,boolean navigate){journey=id;prefs.journey(id);TrackingService.start(this,id);if(navigate){Toast.makeText(this,(distance()<300||weak?"འགྲོ་ལམ་ཟིན་ཐོ་འགོ་བཙུགས། / 轨迹已开始；起点过近或离线会标记审核":"འགྲོ་ལམ་ཟིན་ཐོ་འགོ་བཙུགས། / 轨迹已开始，到达后扫码"),Toast.LENGTH_LONG).show();startActivity(new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP));finish();}else{Bilingual.apply(start,"འགྲོ་ལམ་ཟིན་ཐོ་འགོ་བཙུགས།","正在记录前往轨迹");start.setEnabled(false);scan.setEnabled(true);message.setText("ཨང་རྟགས་བཤེར་ཆོག / 已自动开始记录轨迹，可直接扫码");}}
 // 已到点位可直接扫码，不要求先开启后台轨迹；本地只建立提交所需的轻量行程记录。
 private void scan(){if(here==null){message.setText("ཕྱི་རོལ་དུ་གནས་ས་སྒུག་རོགས། / 请到室外等待定位");return;}if(distance()>task.j.optInt("severe_radius_m",300)){message.setText("300m ལས་བརྒལ། / 超过300米，禁止开始采样");return;}directJourney();scanner.launch(new Intent(this,ScanActivity.class).putExtra("sampleCode",task.code()).putExtra("sampleLabel",task.typeUi().inline()).putExtra("sampleType",task.sampleType()));}
 private void directJourney(){if(journey!=null)return;journey=db.active(task.j.optLong("site_id"));if(journey==null)journey=db.journey(task.id,task.j.optLong("site_id"),new Location(here),!Util.online(this));prefs.journey(journey);}
 private void scanResult(int code,Intent data){if(code!=RESULT_OK||data==null)return;if(data.getBooleanExtra(ScanActivity.DAMAGED,false)){manualDialog();return;}try{QrData q=QrData.parse(data.getStringExtra(ScanActivity.RESULT));if(q.activation||!task.code().equals(q.code))throw new IllegalArgumentException("ཤེལ་དམ་ཨང་གྲངས་མི་མཐུན། / 瓶子编号不匹配，应为 "+task.code());qr=q.token;manual=false;noWater=false;ready();}catch(Exception e){message.setText(e.getMessage()+"\nཤེལ་དམ་ཡང་དག་བརྗེ་ནས་བཤེར། / 请换正确瓶子重扫");}}
 private void manualDialog(){LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(32,8,32,0);EditText code=new EditText(this);code.setHint("1　ཨང་གྲངས་ཆ་ཚང་། / 完整输入 "+task.code());EditText note=new EditText(this);note.setHint("2　ཆག་སྐྱོན་གསལ་བཤད། / 说明标签损坏情况");body.addView(code);body.addView(note);new AlertDialog.Builder(this).setTitle("ཨང་རྟགས་ཆག་སྐྱོན། / 二维码损坏（严重可疑）").setMessage("3　པར་ནང་ཆག་སྐྱོན་ཨང་རྟགས་ཡོད་དགོས།\n照片中必须拍到损坏标签").setView(body).setPositiveButton("ངེས་གཏན། / 确认",(d,w)->{if(!task.code().equals(code.getText().toString().trim())){message.setText("ཨང་གྲངས་ཆ་ཚང་མཐུན་དགོས། / 编号必须完全一致");return;}manual=true;noWater=false;reason="二维码损坏";detail=note.getText().toString().trim();ready();}).setNegativeButton("ཕྱིར་འཐེན། / 取消",null).show();}
 private void ready(){photoButton.setVisibility(View.VISIBLE);double d=distance();if(manual)message.setText("ཆག་སྐྱོན་ཨང་རྟགས་ཉེ་སར་བཞག་ནས་ས་གནས་པར་ལེན། / 损坏标签放近处，后方拍实际环境");else if(d>task.j.optInt("normal_radius_m",30))message.setText(String.format(Locale.CHINA,"ཨང་རྟགས་ཡང་དག　·　བར་ཐག %.0f m\n二维码正确；超过30米，系统记录距离供审核。装水后拍瓶子与现场环境",d));else message.setText("ཨང་རྟགས་ཡང་དག　·　ཤེལ་དམ་དང་ས་གནས་པར་རྒྱོབ། / 二维码正确，装水后拍瓶子与现场环境");}
 // 距离超过30米不再要求选择原因（需求变更）：照常允许拍照采样，
 // 服务器按实际距离自动打 distance_30_80m / distance_80_300m 风险标志供管理员审核。
 private void noWater(){if(here==null){message.setText("ཕྱི་རོལ་དུ་གནས་ས་སྒུག་རོགས། / 请到室外等待定位");return;}if(distance()>task.j.optInt("severe_radius_m",300)){message.setText("300m ལས་བརྒལ། / 超过300米，禁止提交");return;}directJourney();new AlertDialog.Builder(this).setTitle("དཔེ་ཚད་ལེན་མི་ཐུབ་པའི་རྒྱུ་མཚན། / 无法采样原因").setSingleChoiceItems(REASON_LABELS,0,null).setPositiveButton("མུ་མཐུད་པར་རྒྱོབ། / 继续拍现场",(d,w)->{int x=((AlertDialog)d).getListView().getCheckedItemPosition();reason=x<0?"无水":REASONS[x];noWater=true;manual=false;qr="";Bilingual.apply(photoButton,"3 དཔེ་ཚད་ལེན་མི་ཐུབ་པའི་ས་གནས་པར་རྒྱོབ།","拍摄无法采样的现场");photoButton.setVisibility(View.VISIBLE);message.setText("ཤེལ་དམ་མི་དགོས། ས་གནས་དངོས་པར་ལེན། / 无水记录无需瓶子，只拍实际现场");}).setNegativeButton("ཕྱིར་འཐེན། / 取消",null).show();}
 private void photo(){if(here==null)return;ui.removeCallbacks(autoTick);Intent i=new Intent(this,PhotoActivity.class).putExtra("project",task.j.optString("project_name")).putExtra("code",task.code()).putExtra("type",task.typeUi().inline()).putExtra("site",Bilingual.inline(task.titleBo(),task.title())).putExtra("siteCode",task.siteCode()).putExtra("lat",here.getLatitude()).putExtra("lon",here.getLongitude()).putExtra("accuracy",(double)here.getAccuracy()).putExtra("distance",distance());camera.launch(i);}
 private void photoResult(int code,Intent data){if(code!=RESULT_OK||data==null)return;photo=data.getStringExtra(PhotoActivity.PATH);captured=data.getStringExtra(PhotoActivity.AT);weather=data.getStringExtra(PhotoActivity.WEATHER);if(photo==null||!new File(photo).isFile()){message.setText("པར་ཉར་མ་ཐུབ། ཡང་བསྐྱར་པར་རྒྱོབ། / 照片保存失败，请重拍");return;}save();}
 private void save(){ui.removeCallbacks(autoTick);if(here==null||photo.isEmpty())return;try{if(journey==null){journey=db.journey(task.id,task.j.optLong("site_id"),new Location(here),false);prefs.journey(journey);TrackingService.start(this,journey);}JSONObject p=new JSONObject().put("capturedAt",captured).put("latitude",here.getLatitude()).put("longitude",here.getLongitude()).put("accuracyM",here.getAccuracy()).put("weatherText",weather==null?"待补充":weather).put("noWater",noWater).put("manualCode",manual).put("submittedCode",manual?task.code():"").put("qrToken",qr).put("exceptionCategory",reason).put("exceptionDetail",detail).put("mockLocation",Util.mock(here));db.record(task.id,journey,photo,p);db.taskQueued(task.id);String saveDetail="{}";try{saveDetail=new JSONObject().put("taskId",task.id).put("distance",Math.round(distance())).put("noWater",noWater).put("manual",manual).put("queue",db.count("status!='uploaded'")).put("network",Util.networkType(this)).toString();}catch(Exception ignored){}db.log("info","SAVE_QUEUED",saveDetail);boolean sibling=db.sibling(task.j.optLong("site_id"),task.id);if(!sibling){db.finish(journey);TrackingService.stop(this);prefs.journey("");}WorkManager.getInstance(this).enqueue(new OneTimeWorkRequest.Builder(SyncWorker.class).setConstraints(new Constraints.Builder().setRequiredNetworkType(NetworkType.CONNECTED).build()).build());showSaved(Util.online(this));}catch(Exception e){message.setText("ཉར་མ་ཐུབ། ཕྱིར་མ་ཐོན། / 本地保存失败，请不要退出："+e.getMessage());db.log("error","SAVE "+e.getMessage());}}
 private void showSaved(boolean online){save.setEnabled(false);photoButton.setEnabled(false);String detail=online?"ཁ་པར་ནང་ཉར་ཟིན། རྒྱབ་ལྗོངས་ནས་ཡར་འཇུག་བྱེད།\n已保存到手机，正在后台上传。":"ཁ་པར་ནང་ཉར་ཟིན། དྲ་ཡོད་དུས་རང་འགུལ་གྱིས་ཡར་འཇུག\n已保存到手机，联网后自动上传。";new AlertDialog.Builder(this).setTitle("4　ཉར་ཚགས་ཟིན། / 保存成功").setMessage(detail+"\n\n"+task.code()).setPositiveButton("ལས་འགན་ཐོ་གཞུང་། / 返回任务列表",(d,w)->finish()).setCancelable(false).show();}
 private double distance(){return here==null?Double.MAX_VALUE:Util.distance(here.getLatitude(),here.getLongitude(),task.lat(),task.lon());}public void onLocationChanged(@NonNull Location l){here=l;double d=distance();String level=d<=30?"སྤྱི་རྒྱ་30ནང་། / 30米内：正常":d<=80?"སྤྱི་རྒྱ་30—80 / 30～80米：记录审核":d<=300?"སྤྱི་རྒྱ་80—300 / 80～300米：严重可疑":"སྤྱི་རྒྱ་300ལས་བརྒལ། / 超过300米：禁止";loc.setText(String.format(Locale.CHINA,"བར་ཐག %.0f m · ཞིབ་ཚད ±%.0f m\n距点 %.0f米 · 精度±%.0f米\n%s%s",d,l.getAccuracy(),d,l.getAccuracy(),level,Util.mock(l)?"\nརྫུན་བཟོས་གནས་ས་ཟིན་ཐོ་བཀོད། / 模拟位置已被系统记录":""));}
 private void submittedPhoto(){if(!task.submitted())return;ImageView image=findViewById(R.id.uploadedPhoto);TextView info=findViewById(R.id.uploadInfo);JSONObject local=db.recordForTask(task.id);JSONObject payload=local==null?null:local.optJSONObject("payload");String path=task.j.optString("photo_path","");if(local!=null&&!local.optString("photo","").isEmpty()&&new File(local.optString("photo")).isFile())path=local.optString("photo");String captured=task.j.optString("captured_at","");if(captured.isEmpty()&&payload!=null)captured=payload.optString("capturedAt","");double distance=task.j.optDouble("record_distance_m",Double.NaN);if(Double.isNaN(distance)&&payload!=null)distance=Util.distance(payload.optDouble("latitude"),payload.optDouble("longitude"),task.lat(),task.lon());String weather=task.j.optString("server_weather_text","");if(weather.isEmpty())weather=task.j.optString("weather_text","");if(weather.isEmpty()&&payload!=null)weather=payload.optString("weatherText","");String exception=task.j.optString("exception_detail","");if(exception.isEmpty())exception=task.j.optString("exception_category","");String review=task.j.optString("review_status","");StringBuilder details=new StringBuilder("用户采样记录");if(!captured.isEmpty())details.append("\n拍摄时间 ").append(captured.replace('T',' '));if(!Double.isNaN(distance))details.append(String.format(Locale.CHINA,"\n距点 %.0f 米",distance));String accuracy=task.j.optString("record_accuracy_m","");if(!accuracy.isEmpty())details.append(" · 精度±").append(String.format(Locale.CHINA,"%.0f",task.j.optDouble("record_accuracy_m"))).append(" 米");if(!weather.isEmpty())details.append("\n天气 ").append(weather);if(!exception.isEmpty())details.append("\n异常说明 ").append(exception);if(task.j.optBoolean("no_water")||(payload!=null&&payload.optBoolean("noWater")))details.append("\n采样结果：现场无水");if(!review.isEmpty())details.append("\n审核状态 ").append(review);info.setText(details.toString());info.setVisibility(View.VISIBLE);if(path==null||path.isEmpty())return;loadImage(path,image,"用户采样图片");}
 private void loadImage(String path,ImageView target,String description){if(path==null||path.isEmpty()){target.setVisibility(View.GONE);return;}if(new File(path).isFile()){Bitmap bm=BitmapFactory.decodeFile(path);if(bm!=null){target.setTag(bm);target.setImageBitmap(bm);target.setVisibility(View.VISIBLE);target.setOnClickListener(v->showImage(bm,description));}return;}work.execute(()->{try(Response r=new OkHttpClient().newCall(new Request.Builder().url(path.startsWith("http")?path:prefs.server()+path).build()).execute()){if(!r.isSuccessful()||r.body()==null)return;byte[] b=r.body().bytes();Bitmap bm=BitmapFactory.decodeByteArray(b,0,b.length);runOnUiThread(()->{if(bm==null)return;target.setTag(bm);target.setImageBitmap(bm);target.setVisibility(View.VISIBLE);target.setOnClickListener(v->showImage(bm,description));});}catch(Exception e){db.log("warning","IMAGE "+e.getMessage());}});}
 private void showImage(Bitmap bm,String description){android.app.Dialog d=new android.app.Dialog(this);ImageView iv=new ImageView(this);iv.setImageBitmap(bm);iv.setScaleType(ImageView.ScaleType.FIT_CENTER);iv.setBackgroundColor(0xFF000000);iv.setContentDescription(description);d.setContentView(iv);iv.setOnClickListener(v->d.dismiss());d.show();}
 private void reference(){String path=task.j.optString("reference_image");ImageView ref=findViewById(R.id.reference);if(path==null||path.isEmpty()){ref.setVisibility(View.GONE);return;}
  // 点击参考图全屏放大查看（村民在山里要对照细节），再点一下关闭。
  ref.setOnClickListener(x->{android.graphics.Bitmap bm=(android.graphics.Bitmap)ref.getTag();if(bm==null)return;android.app.Dialog d=new android.app.Dialog(this);ImageView iv=new ImageView(this);iv.setImageBitmap(bm);iv.setScaleType(ImageView.ScaleType.FIT_CENTER);iv.setBackgroundColor(0xFF000000);d.setContentView(iv);iv.setOnClickListener(y->d.dismiss());d.show();});
  work.execute(()->{try(Response r=new OkHttpClient().newCall(new Request.Builder().url(path.startsWith("http")?path:prefs.server()+path).build()).execute()){if(!r.isSuccessful()||r.body()==null){runOnUiThread(()->ref.setVisibility(View.GONE));return;}byte[] b=r.body().bytes();android.graphics.Bitmap bm=BitmapFactory.decodeByteArray(b,0,b.length);runOnUiThread(()->{if(bm==null)ref.setVisibility(View.GONE);else{ref.setTag(bm);ref.setImageBitmap(bm);ref.setVisibility(View.VISIBLE);}});}catch(Exception e){db.log("warning","REFERENCE "+e.getMessage());runOnUiThread(()->ref.setVisibility(View.GONE));}});}
 protected void onDestroy(){try{lm.removeUpdates(this);}catch(Exception ignored){}ui.removeCallbacks(autoTick);work.shutdown();super.onDestroy();}
}
