package online.gpsgps.bscsampling;

import android.Manifest;import android.app.AlertDialog;import android.content.*;import android.content.pm.PackageManager;import android.graphics.BitmapFactory;import android.location.*;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.view.View;import android.widget.*;import androidx.activity.result.*;import androidx.activity.result.contract.ActivityResultContracts;import androidx.annotation.NonNull;import androidx.appcompat.app.AppCompatActivity;import androidx.core.app.ActivityCompat;import androidx.core.content.ContextCompat;import androidx.work.*;import com.google.android.material.button.MaterialButton;import org.json.JSONObject;import java.io.File;import java.util.Locale;import java.util.concurrent.*;import okhttp3.*;

public final class TaskActivity extends AppCompatActivity implements LocationListener{
 private static final String[] REASONS={"无水","河岸无法靠近","道路中断","水位或地质危险","二维码损坏","其他"};private Store db;private Prefs prefs;private Task task;private LocationManager lm;private Location here;private String journey,qr="",reason="",detail="",photo="",captured="",weather="待补充";private boolean manual,noWater;private TextView loc,message;private MaterialButton start,scan,photoButton,save;private ImageView preview;private final ExecutorService work=Executors.newSingleThreadExecutor();private final Handler ui=new Handler(Looper.getMainLooper());private int autoLeft;private final Runnable autoTick=new Runnable(){public void run(){if(autoLeft<=0){save();return;}message.setText("照片已拍摄："+autoLeft+" 秒后自动保存（点重新拍照取消）");autoLeft--;ui.postDelayed(this,1000);}};
 private final ActivityResultLauncher<String[]> foreground=registerForActivityResult(new ActivityResultContracts.RequestMultiplePermissions(),r->permissionGuide());private final ActivityResultLauncher<Intent> scanner=registerForActivityResult(new ActivityResultContracts.StartActivityForResult(),r->scanResult(r.getResultCode(),r.getData()));private final ActivityResultLauncher<Intent> camera=registerForActivityResult(new ActivityResultContracts.StartActivityForResult(),r->photoResult(r.getResultCode(),r.getData()));
 protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_task);db=new Store(this);prefs=new Prefs(this);task=db.task(getIntent().getLongExtra("task",-1));if(task==null){Toast.makeText(this,"任务不存在，请同步",Toast.LENGTH_LONG).show();finish();return;}lm=getSystemService(LocationManager.class);bind();fill();locations();reference();journey=db.active(task.j.optLong("site_id"));if(journey!=null){start.setText("正在记录前往轨迹");start.setEnabled(false);scan.setEnabled(true);}}
 private void bind(){findViewById(R.id.back).setOnClickListener(v->finish());loc=findViewById(R.id.locationState);message=findViewById(R.id.message);start=findViewById(R.id.start);scan=findViewById(R.id.scanBottle);photoButton=findViewById(R.id.takePhoto);save=findViewById(R.id.save);preview=findViewById(R.id.photoPreview);start.setOnClickListener(v->start());scan.setOnClickListener(v->scan());findViewById(R.id.noWater).setOnClickListener(v->noWater());photoButton.setOnClickListener(v->photo());save.setOnClickListener(v->save());}
 private void fill(){((TextView)findViewById(R.id.taskTitle)).setText(task.title());((TextView)findViewById(R.id.code)).setText(task.code());((TextView)findViewById(R.id.meta)).setText("历史序号 "+task.siteCode()+" · "+Util.type(task.j.optString("sample_type"))+" · 计划 "+task.j.optString("planned_date"));((TextView)findViewById(R.id.instructions)).setText("管理员说明\n"+task.j.optString("instructions","无")+"\n\n备注\n"+task.j.optString("remarks","无"));((TextView)findViewById(R.id.risk)).setText("风险提醒\n"+task.j.optString("risk_note","注意水边安全")+(task.canceled()?"\n⚠任务已取消：仍可提交，但进入审核":""));}
 private void locations(){if(ActivityCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){foreground.launch(Build.VERSION.SDK_INT>=33?new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.POST_NOTIFICATIONS}:new String[]{Manifest.permission.ACCESS_FINE_LOCATION});return;}try{lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,2000,0,this);if(lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER))lm.requestLocationUpdates(LocationManager.NETWORK_PROVIDER,3000,0,this);}catch(Exception e){message.setText("定位启动失败："+e.getMessage());}}
 private boolean permissions(){return ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED&&(Build.VERSION.SDK_INT<29||ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_BACKGROUND_LOCATION)==PackageManager.PERMISSION_GRANTED)&&(Build.VERSION.SDK_INT<33||ContextCompat.checkSelfPermission(this,Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED);}
 private void permissionGuide(){if(permissions()){locations();message.setText("权限已开启");return;}new AlertDialog.Builder(this).setTitle("必须开启定位与通知").setMessage("为了证明真实前往采样点，需要：\n1. 精确位置：允许\n2. 位置信息：始终允许\n3. 通知：允许\n\n请不要选择“仅本次”。开启后返回再点开始。 ").setPositiveButton("去开启",(d,w)->startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())))).setNegativeButton("暂不采样",null).show();}
 private void start(){if(!permissions()){db.log("warning","PERM_DENIED_START",permDetail());permissionGuide();return;}if(here==null){message.setText("请到室外等待卫星定位");return;}db.log("info","START_JOURNEY",permDetail());String shared=db.active(task.j.optLong("site_id"));if(shared!=null){activate(shared,false,true);return;}start.setEnabled(false);start.setText("正在建立轨迹…");Location pos=new Location(here);if(!Util.online(this)){activate(db.journey(task.id,task.j.optLong("site_id"),pos,true),true,true);return;}work.execute(()->{String local=db.journey(task.id,task.j.optLong("site_id"),pos,false);try{JSONObject r=new Api(this).start(task.id,pos.getLatitude(),pos.getLongitude(),pos.getAccuracy());db.serverJourney(local,r.getJSONObject("journey").getLong("id"));runOnUiThread(()->activate(local,r.optBoolean("weakEvidence"),true));}catch(Api.ApiError e){db.abort(local);runOnUiThread(()->{start.setEnabled(true);start.setText("可选：开始前往（记录轨迹）");message.setText(e.getMessage());});}catch(Exception e){db.offlineJourney(local);db.log("warning","OFFLINE_START "+e.getMessage());runOnUiThread(()->activate(local,true,true));}});}
 private String permDetail(){try{return new org.json.JSONObject().put("network",Util.networkType(this)).put("online",Util.online(this)).put("distance",Math.round(distance())).put("fineLocation",ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED).put("backgroundLocation",ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_BACKGROUND_LOCATION)==PackageManager.PERMISSION_GRANTED).toString();}catch(Exception e){return"{}";}}
 private void activate(String id,boolean weak,boolean navigate){journey=id;prefs.journey(id);TrackingService.start(this,id);if(navigate){Toast.makeText(this,(distance()<300||weak?"轨迹记录已开始（起点距采样点不足300米或离线开始，将标记审核）":"轨迹记录已开始，每10秒保存位置。到达后扫码"),Toast.LENGTH_LONG).show();startActivity(new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP));finish();}else{start.setText("正在记录前往轨迹");start.setEnabled(false);scan.setEnabled(true);message.setText("已自动开始记录轨迹，可直接扫码");}}
 // 已到点位可直接扫码，不要求先开启后台轨迹；本地只建立提交所需的轻量行程记录。
 private void scan(){if(here==null){message.setText("请到室外等待定位");return;}if(distance()>task.j.optInt("severe_radius_m",300)){message.setText("超过300米，禁止开始采样");return;}directJourney();scanner.launch(new Intent(this,ScanActivity.class));}
 private void directJourney(){if(journey!=null)return;journey=db.active(task.j.optLong("site_id"));if(journey==null)journey=db.journey(task.id,task.j.optLong("site_id"),new Location(here),!Util.online(this));prefs.journey(journey);}
 private void scanResult(int code,Intent data){if(code!=RESULT_OK||data==null)return;if(data.getBooleanExtra(ScanActivity.DAMAGED,false)){manualDialog();return;}try{QrData q=QrData.parse(data.getStringExtra(ScanActivity.RESULT));if(q.activation||!task.code().equals(q.code))throw new IllegalArgumentException("瓶子编号不匹配，应为 "+task.code());qr=q.token;manual=false;noWater=false;ready();}catch(Exception e){message.setText(e.getMessage()+"，请换正确瓶子重扫");}}
 private void manualDialog(){LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(32,8,32,0);EditText code=new EditText(this);code.setHint("完整输入 "+task.code());EditText note=new EditText(this);note.setHint("说明标签损坏情况");body.addView(code);body.addView(note);new AlertDialog.Builder(this).setTitle("二维码损坏（严重可疑）").setMessage("照片中必须拍到损坏标签").setView(body).setPositiveButton("确认",(d,w)->{if(!task.code().equals(code.getText().toString().trim())){message.setText("编号必须完全一致");return;}manual=true;noWater=false;reason="二维码损坏";detail=note.getText().toString().trim();ready();}).setNegativeButton("取消",null).show();}
 private void ready(){photoButton.setVisibility(View.VISIBLE);double d=distance();if(manual)message.setText("损坏标签放近处，后方拍实际环境");else if(d>task.j.optInt("normal_radius_m",30))message.setText(String.format(Locale.CHINA,"二维码正确。距采样点 %.0f 米（超过30米，系统自动记录距离供管理员审核）。装水后拍瓶子与现场环境",d));else message.setText("二维码正确。装水后拍瓶子与现场环境");}
 // 距离超过30米不再要求选择原因（需求变更）：照常允许拍照采样，
 // 服务器按实际距离自动打 distance_30_80m / distance_80_300m 风险标志供管理员审核。
 private void noWater(){if(here==null){message.setText("请到室外等待定位");return;}if(distance()>task.j.optInt("severe_radius_m",300)){message.setText("超过300米，禁止提交");return;}directJourney();new AlertDialog.Builder(this).setTitle("无法采样原因").setSingleChoiceItems(REASONS,0,null).setPositiveButton("继续拍现场",(d,w)->{int x=((AlertDialog)d).getListView().getCheckedItemPosition();reason=x<0?"无水":REASONS[x];noWater=true;manual=false;qr="";photoButton.setText("拍摄无法采样的现场");photoButton.setVisibility(View.VISIBLE);message.setText("无水记录无需瓶子，只拍实际现场");}).setNegativeButton("取消",null).show();}
 private void photo(){if(here==null)return;ui.removeCallbacks(autoTick);Intent i=new Intent(this,PhotoActivity.class).putExtra("project",task.j.optString("project_name")).putExtra("code",task.code()).putExtra("type",Util.type(task.j.optString("sample_type"))).putExtra("site",task.title()).putExtra("siteCode",task.siteCode()).putExtra("lat",here.getLatitude()).putExtra("lon",here.getLongitude()).putExtra("accuracy",(double)here.getAccuracy()).putExtra("distance",distance());camera.launch(i);}
 private void photoResult(int code,Intent data){if(code!=RESULT_OK||data==null)return;photo=data.getStringExtra(PhotoActivity.PATH);captured=data.getStringExtra(PhotoActivity.AT);weather=data.getStringExtra(PhotoActivity.WEATHER);if(photo==null||!new File(photo).isFile()){message.setText("照片保存失败，请重拍");return;}preview.setImageBitmap(BitmapFactory.decodeFile(photo));preview.setVisibility(View.VISIBLE);save.setVisibility(View.VISIBLE);photoButton.setText("重新拍照");autoLeft=10;ui.removeCallbacks(autoTick);ui.postDelayed(autoTick,1000);}
 private void save(){ui.removeCallbacks(autoTick);if(here==null||photo.isEmpty())return;try{if(journey==null){journey=db.journey(task.id,task.j.optLong("site_id"),new Location(here),false);prefs.journey(journey);TrackingService.start(this,journey);}JSONObject p=new JSONObject().put("capturedAt",captured).put("latitude",here.getLatitude()).put("longitude",here.getLongitude()).put("accuracyM",here.getAccuracy()).put("weatherText",weather==null?"待补充":weather).put("noWater",noWater).put("manualCode",manual).put("submittedCode",manual?task.code():"").put("qrToken",qr).put("exceptionCategory",reason).put("exceptionDetail",detail).put("mockLocation",Util.mock(here));db.record(task.id,journey,photo,p);db.taskQueued(task.id);String saveDetail="{}";try{saveDetail=new JSONObject().put("taskId",task.id).put("distance",Math.round(distance())).put("noWater",noWater).put("manual",manual).put("queue",db.count("status!='uploaded'")).put("network",Util.networkType(this)).toString();}catch(Exception ignored){}db.log("info","SAVE_QUEUED",saveDetail);boolean sibling=db.sibling(task.j.optLong("site_id"),task.id);if(!sibling){db.finish(journey);TrackingService.stop(this);prefs.journey("");}WorkManager.getInstance(this).enqueue(new OneTimeWorkRequest.Builder(SyncWorker.class).setConstraints(new Constraints.Builder().setRequiredNetworkType(NetworkType.CONNECTED).build()).build());Toast.makeText(this,Util.online(this)?"已保存，正在后台上传"+(sibling?"（同点还有任务，轨迹继续记录）":""):"已保存，联网后自动上传"+(sibling?"（同点还有任务，轨迹继续记录）":""),Toast.LENGTH_LONG).show();finish();}catch(Exception e){message.setText("本地保存失败，请不要退出："+e.getMessage());db.log("error","SAVE "+e.getMessage());}}
 private double distance(){return here==null?Double.MAX_VALUE:Util.distance(here.getLatitude(),here.getLongitude(),task.lat(),task.lon());}public void onLocationChanged(@NonNull Location l){here=l;double d=distance();String level=d<=30?"30米内：正常":d<=80?"30～80米：需写原因":d<=300?"80～300米：严重可疑":"超过300米：禁止";loc.setText(String.format(Locale.CHINA,"WGS84 %.6f, %.6f\n距点 %.0f米 · 精度±%.0f米\n%s%s",l.getLatitude(),l.getLongitude(),d,l.getAccuracy(),level,Util.mock(l)?"\n⚠检测到模拟位置":""));}
 private void reference(){String path=task.j.optString("reference_image");ImageView ref=findViewById(R.id.reference);if(path==null||path.isEmpty()){ref.setVisibility(View.GONE);return;}
  // 点击参考图全屏放大查看（村民在山里要对照细节），再点一下关闭。
  ref.setOnClickListener(x->{android.graphics.Bitmap bm=(android.graphics.Bitmap)ref.getTag();if(bm==null)return;android.app.Dialog d=new android.app.Dialog(this);ImageView iv=new ImageView(this);iv.setImageBitmap(bm);iv.setScaleType(ImageView.ScaleType.FIT_CENTER);iv.setBackgroundColor(0xFF000000);d.setContentView(iv);iv.setOnClickListener(y->d.dismiss());d.show();});
  work.execute(()->{try(Response r=new OkHttpClient().newCall(new Request.Builder().url(path.startsWith("http")?path:prefs.server()+path).build()).execute()){if(!r.isSuccessful()||r.body()==null){runOnUiThread(()->ref.setVisibility(View.GONE));return;}byte[] b=r.body().bytes();android.graphics.Bitmap bm=BitmapFactory.decodeByteArray(b,0,b.length);runOnUiThread(()->{if(bm==null)ref.setVisibility(View.GONE);else{ref.setTag(bm);ref.setImageBitmap(bm);ref.setVisibility(View.VISIBLE);}});}catch(Exception e){db.log("warning","REFERENCE "+e.getMessage());runOnUiThread(()->ref.setVisibility(View.GONE));}});}
 protected void onDestroy(){try{lm.removeUpdates(this);}catch(Exception ignored){}ui.removeCallbacks(autoTick);work.shutdown();super.onDestroy();}
}
