package online.gpsgps.bscsampling;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.location.*;import android.os.*;import androidx.annotation.*;import androidx.core.app.*;import androidx.core.content.ContextCompat;import androidx.work.*;import org.json.JSONObject;import java.util.Locale;import java.util.concurrent.*;

public final class TrackingService extends Service implements LocationListener{
  static final String START="bsc.START",STOP="bsc.STOP",EXTRA="journey",EXTRA_RESUME="resume";private LocationManager lm;private Store db;private Prefs prefs;private String id;private int seq;private long lastLive;private final ExecutorService net=Executors.newSingleThreadExecutor();
  static void start(Context c,String id){ContextCompat.startForegroundService(c,new Intent(c,TrackingService.class).setAction(START).putExtra(EXTRA,id));}
  static void startResumed(Context c,String id){ContextCompat.startForegroundService(c,new Intent(c,TrackingService.class).setAction(START).putExtra(EXTRA,id).putExtra(EXTRA_RESUME,true));}
  static void stop(Context c){c.startService(new Intent(c,TrackingService.class).setAction(STOP));}
  public void onCreate(){super.onCreate();lm=getSystemService(LocationManager.class);db=new Store(this);prefs=new Prefs(this);}
  public int onStartCommand(Intent in,int flags,int start){if(in!=null&&STOP.equals(in.getAction())){stopNow();return START_NOT_STICKY;}boolean resumed=(in!=null&&in.getBooleanExtra(EXTRA_RESUME,false))||in==null;id=in==null?prefs.activeJourney():in.getStringExtra(EXTRA);if(id==null||id.isEmpty()||db.journey(id)==null){stopSelf();return START_NOT_STICKY;}prefs.journey(id);seq=db.nextSeq(id);startForeground(301,note("每10秒保存一次WGS84位置"));if(ActivityCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){db.log("error","TRACK_PERMISSION_MISSING",trackDetail(resumed));stopSelf();return START_NOT_STICKY;}try{lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,10000,0,this,Looper.getMainLooper());if(lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER))lm.requestLocationUpdates(LocationManager.NETWORK_PROVIDER,10000,0,this,Looper.getMainLooper());}catch(Exception e){db.log("error","TRACK_START "+e.getMessage(),trackDetail(resumed));}if(resumed){db.log("warning","TRACK_RESUME",trackDetail(true));JSONObject j=db.journey(id);if(j!=null&&j.has("serverId")){final long serverId=j.optLong("serverId");net.execute(()->{try{new Api(this).interrupted(serverId);}catch(Exception e){db.log("warning","TRACK_INTERRUPT_MARK "+e.getMessage());}});}}else db.log("info","TRACK_START",trackDetail(false));return START_STICKY;}
  private String trackDetail(boolean resumed){try{return new JSONObject().put("journey",id).put("network",Util.networkType(this)).put("resumed",resumed).put("seq",seq).toString();}catch(Exception e){return"{}";}}
  private Notification note(String text){PendingIntent open=PendingIntent.getActivity(this,0,new Intent(this,MainActivity.class),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);PendingIntent stop=PendingIntent.getService(this,1,new Intent(this,TrackingService.class).setAction(STOP),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);return new NotificationCompat.Builder(this,SamplingApp.TRACK).setSmallIcon(R.drawable.ic_launcher).setContentTitle("巴松措采样：轨迹记录中").setContentText(text).setOngoing(true).setContentIntent(open).addAction(0,"停止记录",stop).build();}
  public void onLocationChanged(@NonNull Location l){db.track(id,seq++,l);if(seq%60==0)db.log("info","TRACK_PROGRESS","{\"points\":"+seq+"}");getSystemService(NotificationManager.class).notify(301,note(String.format(Locale.CHINA,"WGS84 %.6f, %.6f · ±%.0fm",l.getLatitude(),l.getLongitude(),l.getAccuracy())));if(System.currentTimeMillis()-lastLive>=30000&&Util.online(this)){lastLive=System.currentTimeMillis();JSONObject j=db.journey(id);if(j!=null&&j.has("serverId"))net.execute(()->{try{new Api(this).live(j.optLong("taskId"),new JSONObject().put("recordedAt",Util.now()).put("latitude",l.getLatitude()).put("longitude",l.getLongitude()).put("accuracyM",l.getAccuracy()));}catch(Exception e){db.log("warning","LIVE "+e.getMessage());}});WorkManager.getInstance(this).enqueue(new OneTimeWorkRequest.Builder(SyncWorker.class).setConstraints(new Constraints.Builder().setRequiredNetworkType(NetworkType.CONNECTED).build()).build());}}
  private void stopNow(){try{lm.removeUpdates(this);}catch(Exception ignored){}prefs.journey("");stopForeground(STOP_FOREGROUND_REMOVE);stopSelf();}
  public void onProviderDisabled(@NonNull String p){db.log("warning","GPS_DISABLED "+p);}public void onProviderEnabled(@NonNull String p){}@Nullable public IBinder onBind(Intent i){return null;}public void onDestroy(){try{lm.removeUpdates(this);}catch(Exception ignored){}net.shutdown();super.onDestroy();}
}
